gen_data['Gamma_World_Adventure'] = [
	'The team is hired to scout out a {GWLocation} that is {GWCondition} and {GWDilemma}. While in route they will run into group of {GWCultureStructure} {GWDemiHumanity} who are focused on {GWCulturePurposeEconomy}.  They live in a {GWLocation} called {GWCityFirstName}{GWCitySecondName} that is {GWCitySpecialCondition}.  In route they will be ambushed by a group of {GWCultureStructure} {GWDemiHumanity} who are focused on {GWCulturePurposeEconomy} at a {GWTerrain} and {GWRuse}'
]


gen_data['GWLocation'] = [
'House',
'Camp Site',
'Storage Center',
'Grocery Store',
'Specialty Store',
'Shopping Mall',
'Sports Arena',
'Church',
'Office Building',
'Sky Scraper',
'Airport',
'Army Depot',
'Army Base',
'Fallout Shelter',
'Underground Lab',
'Underground Base',
'Science Lab',
'Crashed Alien Ship',
'City Sewers',
'Sheriff’s Station',
'Crater',
'Ravine',
'Forest',
'Boulder-strewn Field',
'Mountain Trail',
'Mountain Top',
'Lake',
'Pond',
'Seashore',
'Shallow Cave',
'Deep Cave',
'Complex Cave',
'Crevice',
'Garbage Dump',
'Farmstead',
'Grassy Valley',
'Murky Swamp',
'Flood Plain',
'Subway Tunnels',
'Train Station',
'Small Power Plant',
'Hydro-electric Dam',
'Nuclear Power Plant',
'Gas Station',
'Baseball/Soccer Field',
'Docks',
'Shipyard',
'Monument',
'Giant Tree',
'Big Hole in Ground',
'Garbage Fort',
'Walled-off Community',
'Old Well',
'Oil Rig',
'Nuclear Vessel',
'Steel Mill',
'Cattle Ranch',
'Greenhouse',
'City Park',
'City Zoo',
'Mansion House',
'Golf Course',
'Amusement Park',
'Freeway Overpass',
'Public School',
'College Campus',
'Arboretum',
'Aircraft Hanger',
'Museum',
'Arid Waste',
'Derelict Ship',
'Derelict Aircraft',
'Car Fort',
'Walled Camp',
'Abandoned Train',
'Beached Cruise Ship',
'Beached Submarine',
'Launch Platform',
'Post Office',
'Public Library',
'National Library',
'County Jail',
'Prison Complex',
'Small Casino',
'Grand Casino',
'Motel',
'Hotel',
'Grand Hotel',
'Trailer Park',
'Suburb',
'Apartment Complex',
'Fast Food Place',
'Restaurant',
'Bowling Alley',
'Race Track',
'Hospital',
'Mechanic Shop',
'Convention Center',
'Water Tower',
'Giant Alien Ship'
]
gen_data['GWCondition'] = [
'Abandoned',
'On fire',
'Filled with nuclear waste',
'Crumbling and caving in',
'Infested (Bugs)',
'Infested (Beasts)',
'Infested (Plants)',
'Infested (Rodents)',
'Infested (Robots)',
'Infested (Zombies)',
'Underground',
'Underwater',
'Waterlogged',
'Muddy',
'Flickering Power Source',
'Filled with Garbage',
'Filled with Death/Carnage',
'Filled with Holes',
'Filled with Sand',
'Overgrown with plants',
'Overgrown with moss',
'Overgrown with fungus',
'Overgrown with organic matter',
'Burned Out/Charred',
'Riddled with Bullets',
'Stinking gas fills the air',
'Poison gas fills the air',
'Flammable gas fills the air',
'Radioactive haze fills the air',
'Washed ashore on beach',
'Devoid of light',
'Filled with bright lights',
'Shifting foundation',
'Teetering and ready to fall',
'Covered in graffiti',
'Covered in warning signs',
'Sealed off with barbed wire',
'Sealed off with razor wire',
'Filled with landmines',
'Filled with sinkholes',
'Divided by fissures',
'Half-buried by landslide',
'Assailed by strong winds',
'Threatened by electrical storm',
'Drowning in rainstorm',
'Drenched in acid rainstorm',
'Sinking in the mud',
'Slowly succumbing to rust',
'Permeated by radiation',
'Sinking in the Ground',
'Sinking in the Water',
'About to fall over a cliff',
'About to fall into water',
'Corroding in an acid lake',
'Surrounded by trees',
'Trapped under wreckage',
'Surrounded by animal bones',
'Filled with giant monster bones',
'Surrounded by refugees',
'Surrounded by mannequins',
'Covered with doomsday signs',
'Disturbed by shaking ground',
'Filled with hallucinatory fog',
'Surrounded by ruined vehicles',
'Filled with scorched skeletons',
'Filled with fungal corpses',
'Filthy clothes are strewn about',
'Rotten food crates lay about',
'Covered in strange slime',
'Full of counterfeit money',
'A cyclone is drawing near',
'Entrances are blocked by cars',
'Furniture is stacked all around',
'Surrounded by heads on poles',
'Permeated by a strong odor',
'Bugs drop from the ceiling',
'Covered in makeshift housing',
'Being excavated for supplies',
'Being built on by a community',
'Being fortified by militants',
'Surrounded by tall grass',
'Strange music fills the air',
'Strange singing fills the air',
'Has a strange, sealed door',
'Hides a bunker entrance',
'Surrounded by small camps',
'Protected by tripwires',
'Has been remade into a shrine',
'Has been stripped bare',
'Strange people stand around',
'Filled with organic growths',
'Protected by electric fences',
'Obscured by smoke plumes',
'Harsh laughter fills the air',
'Has an unexploded bomb',
'Lights flicker on and off',
'Loud groaning fills the air',
'A putrid stream runs through it',
'A putrid river runs through it',
'Skulls are piled all around'
]
gen_data['GWDilemma'] = [
'Wired to explode',
'Bandits use it as a base camp',
'Needs to be swept and made safe',
'Giant insects built a hive there',
'Strange monsters were sighted there',
'Find a lost person there',
'Recover lost property there',
'Recover an artifact there',
'Recover data there',
'Recover biological sample there',
'Recover plants with curative properties',
'Hunt a strange monster there',
'Mercenaries camp there',
'Dangerous animals reproduce there',
'Dangerous robots reproduce there',
'Cannibals use it as a kill zone',
'Mad doctor does experiments there',
'Psychopath uses location for sniping',
'Rampaging robot roams there',
'Militant group is using it as a base',
'Possible alien sighting there',
'Disable powerful machine',
'Disable powerful robot',
'Escort a trade caravan through there',
'Escort a scientist through there',
'Recover old world artifact',
'Recover ammunition/weapons',
'Recover food and supplies',
'Recover tools and materials',
'Recover old world books and literature',
'Recover old world movies and media',
'Recover keys or pass codes',
'Recover medical supplies',
'Recover scientific equipment',
'Activate old machinery',
'Activate old electric/water system',
'Look for valuable scrap material',
'Look for rare minerals or crystals',
'Look for old world body with brief case',
'Look for shipping/flight manifest',
'Contact NPC with information',
'Recover sample of special petroleum',
'Recover sample of special fusion cell',
'Find lost crew members',
'Find lost scout',
'Assassinate a bandit boss',
'Sabotage a motor gang’s bikes and cars',
'Sabotage a powerful robot',
'Sabotage an old world machine',
'Find old photographs',
'Dig up a coffin containing money',
'Search for a rare case of scotch',
'Search for a rare case of cigars',
'Search for preserved food stuff',
'A loner in powered armor stalks about',
'Bandits compete to find treasure',
'Copy a map that was drawn on a wall',
'Help build a fortification',
'Help build housing',
'Help build a greenhouse',
'Help build a water purifier',
'Flush out vermin',
'Flush out gangers',
'Put an end to a rivalry',
'Rescue a hostage or hostages',
'Rescue people stranded there',
'Psycho is throwing grenades',
'Psycho has set up traps everywhere',
'Investigate new organization',
'Might contain a clean water source',
'Investigate possible ghost sighting',
'Clear out dangerous squatters',
'Clear out drug labs',
'Clear out vicious plants',
'Eavesdrop on plotting enemies',
'Recover lost keepsakes',
'Look for package containing salvage',
'Look for educational supplies',
'Retrieve fragile mechanical component',
'Move volatile chemicals to safe zone',
'Retrieve classified map of silo locations',
'Find and transport fuel cells',
'Find and transport gasoline tanks',
'Bring back religious artifact',
'Confirm and acquire alien tech',
'Prevent a robbery',
'Convince enemies to move out',
'Find hidden armaments and move them',
'Repair and deliver a vehicle to its owner',
'Disarm and retrieve the core of a bomb',
'Sneak past sleeping foes to scavenge',
'Capture an enemy alive for interrogation',
'Set up monitoring equipment',
'Set a charge to burry a monster lair',
'Use sensors to locate a lost supply box',
'Make contact with a wary community',
'Make contact with a secret organization',
'Make contact with an intelligent monster',
'Negotiate with mercs to aid a town',
'Negotiate with thugs to allow passage'
]
gen_data['GWCityFirstName'] = [
'Red',
'Blue',
'Green',
'Yellow',
'Orange',
'Black',
'White',
'Brown',
'Grey',
'Beast',
'Nutt',
'Bear',
'Owl',
'Coyote',
'Raccoon',
'Cat',
'Dog',
'Wolf',
'Hound',
'Dung',
'Horse',
'Strong',
'Quick',
'Wise',
'Glory',
'Cross',
'Raccoon',
'Quiet',
'Silent',
'Long',
'Short',
'Wayward',
'Deep',
'Sunrise',
'Sunset',
'Twilight',
'Darkness',
'Starshine',
'Moonlight',
'Sunlight',
'Cloudy',
'Murky',
'Bright',
'Lackluster',
'Lakeshore',
'Wooded',
'Grime',
'Grungy',
'Dingy',
'Dungy',
'Bleak',
'Borrowed',
'Stolen',
'Forked',
'Crooked',
'Jagged',
'Ajee',
'Barren',
'Nestled',
'Crestfallen',
'Wind',
'Sky',
'Valley',
'Arbor',
'Meadow',
'Snowflake',
'Trader',
'Forked',
'Antler',
'Tusk',
'Horn',
'Spire',
'Track',
'Rail',
'Cavern',
'Ever',
'Forever',
'Languish',
'Republic',
'Democratic',
'Sovereign',
'Even',
'Crooked',
'Darkly',
'Lightly',
'Meager',
'Luster',
'Tepid',
'Moonshine',
'Staller',
'Quaint',
'Trappers',
'Stately',
'Everglade',
'Everest',
'Meager',
'Slow',
'Sleepy',
'Groggy',
'Lumber'
]
gen_data['GWCitySecondName'] = [
' Man',
' Camp',
' Hovel',
' Hole',
' Squat',
' Way',
' Beard',
' Skins',
' Fang',
' Claw',
' Tower',
' Flight',
' Flow',
' Trail',
' Wind',
' Home',
' Squalor',
' Rend',
' Fall',
' Springs',
' Wood',
'ing',
'er',
'ly',
'er',
'berg',
'ton',
'ling',
' Stead',
' Wallow',
' Flow',
' Stretch',
' Reach',
' Flow',
' Flowing',
' Way',
' Mountain',
' Rock',
' Hill',
' Tongue',
' Hate',
' Hang',
' Fall',
' Falling',
' Clear',
' Clearing',
' Castle',
' Crosse',
' Fort',
' Fortress',
' Pool',
' Tier',
' Slope',
' Hovel',
' Fastness',
' Slumber',
' Restore ',
' Heim',
' Town',
' Community',
' City',
' Retreat',
' Organization',
' Trap',
' Center',
' Refinery',
' Glide',
' Crater',
' Place',
' Commune',
' Group',
' Party',
' Resort',
' Farm',
' Field',
' Mine',
' Space',
' Respite',
' Haven',
' Base',
' Pad',
' Hole',
' Cove',
' Hideaway',
' Hollow',
' Fort',
' Colony',
' Village',
' Hamlet',
' Hide',
' Refuge',
' Sanctuary',
' Caravan',
' Harbor',
' Spot',
' Tub',
' Lot',
' Bridge',
' Wall',
' Quarry'
]
gen_data['GWCitySpecialCondition'] = [
'well and stable.',
'suffering from an outbreak of disease.',
'troubled with spreading fires.',
'suffering from a water shortage.',
'having an influx of trade.',
'in need for more trade.',
'overpopulated and in need of expansion.',
'underpopulated and in need of more inhabitants.',
'mysteriously abandoned.',
'infested with vermin.',
'troubled by bandits roaming about.',
'ruled by a ruthless tyrant.',
'manipulated by strange cult.',
'regularly attacked by a large creature.',
'in a great need for food.',
'overflowing with an excess food but won’t trade with outsiders.',
'in the midst of a power dispute.',
'in the midst of an election process.',
'mistrustful of outsiders.',
'deeply hateful towards outsiders.',
'deeply hateful towards mutants.',
'deeply hateful towards robots and synthetics.',
'deeply hateful towards normal humans.',
'battered after conflict with another settlement.',
'looking for missing members of the community.',
'in trouble because its supply lines have been cut off by monsters.',
'in trouble because its supply lines have been cut off by raiders.',
'looking to acquire arms and armor.',
'looking to acquire tools and services.',
'in possession of a strange, old-world relic in the middle of town.',
'in possession of an unexploded bomb near or in community.',
'troubled by nearby ruins.',
'practices cannibalism.',
'plagued and baffled by a string of murders.',
'receiving threats from bandit group.',
'in need of mechanical component for machines.',
'looking for data to run machine function.',
'using slaves to build.',
'suffering from acid rain from an old power plant threaten life.',
'suffering from heavy rainfall threatens to flood the community.',
'suffering from a sinkhole that opened in the community.',
'dealing with an unearthed robotics lab that has now resumed functioning.',
'dealing with a dormant military robot that has rebooted.',
'dealing with old drones that have reactivated and fly about.',
'suffering from a volcano that has awakened and spews ash.',
'surrounded by newly formed acid lake.',
'dealing with strange fungal growths that are covering buildings.',
'dealing with a mutated virus that has turned community members into zombies.',
'enslaved by hostile robots controling the community.',
'is struggling with parts of community that are in danger of sinking.',
'dealing with sewers have giant alligators rising up at night.',
'being visited by a strange prophet that speaks of the return of bombs.',
'has a visiting peddler who sells miracle mutagen or medicine.',
'worshipping a strange machine.',
'worshipping a large creature.',
'worshipping an old war vehicle.',
'worshipping a seemingly powerful mutant.',
'built with large walls to keep something sinister out.',
'dealing with a strange mist that settles over the town at night.',
'dealing with people mysteriously wandering off.',
'a town of good bandits who want better things.',
'a town of seemingly normal people with a sinister secret.',
'a community of adolescents and no adults.',
'a town with legends of a great bird.',
'a town with legends of a great beast.',
'a town with legends of a holy mutant.',
'a town with legends of a new end to the world.',
'a town with legends of a new start to the world.',
'a town that fully embraces technology.',
'a town that abhors technology.',
'a town of artists.',
'a town of scientists.',
' town of motorists.',
'a massive wall with no response from inside.',
'a community consisting of only one family.',
'dealing with a strange probe is watching people in town.',
'dealing with people in town who are in some kind of stasis.',
'dealing with an invisible creature or creatures who pester locals.',
'dealing with their water well going mysteriously gone dry.',
'dealing with creatures who have infest the community’s well.',
'dealing with their livestock that are vanishing from grazing grounds.',
'a group of slaves who revolted against their masters.',
'dealing with vermin in the community that are stealing tools.',
'dealing with youth in the community that are stealing from people.',
'dealing with a giant, intelligent monster holds town hostage.',
'a town that has improved food that bandits now seek.',
'dealing with an evil men threatening to detonate explosives.',
'a town of intelligent monsters who want peace.',
'protected by a giant robot stands outside and prevents exit.',
'protected by a giant robot stands guard over community.',
'recieving radio broadcasts that urge folks to flee for their lives.',
'struggling with an alien artifact has appeared and divides the town.',
'dealing with great packs of predatory beasts that have moved in.',
'terrorized by vehicular raiders circling the community.',
'terrorized by a psychopath with a flamethrower that attacks the fields.',
'worried about a giant ant colony that has sprung up in the fields.',
'struggling with crops that are mutating and attacking the farmers.',
'overrun with furry things breeding out of control.',
'overrun with mind-controlling cerebral growths.',
'not a town, but an alien starship.'
]
gen_data['GWDemiHumanity'] = [
'Humans',
'Mild Mutants',
'Moderate Mutants',
'Severe Mutants',
'Robots',
'Androids'
]
gen_data['GWCultureStructure'] = [
'Anarchistic',
'Democratic',
'Tribal',
'Capitalistic',
'Socialistic',
'Minimalistic',
'Theocratic',
'Militaristic',
'Imperialistic',
'Sovereign',
]
gen_data['GWCulturePurposeEconomy'] = [
'Agriculture',
'Agriculture',
'Herding',
'Herding',
'Trade',
'Trade',
'Armorsmiths',
'Weaponsmiths',
'Water Purifiers',
'Slave Traders',
'Bandit Raiders',
'Bandit Raiders',
'Explorers',
'Medical Science',
'Experimenters',
'Cannibalism',
'Mechanics',
'Reconstruction',
'Expansion',
'Technologists'
]
gen_data['GWTerrain '] = [
'Flat Valley',
'Narrow Pass',
'Wide Pass',
'Below High Cliff',
'Above High Cliff',
'Rolling Hills',
'Crossroads',
'Ruined Streets',
'Crumbling City',
'Ruined House',
'Ruined Building',
'Small Shack',
'Sandy Expanse',
'Burnt Forest',
'Sparse Forest',
'Dense Forest',
'Boulder Slopes',
'Large Hole/Crater',
'Beached Ship',
'Sandy Shore'
]
gen_data['GWRuse'] = [
'Nothing visible; enemies hidden behind camouflaged blinds.',
'Distress smoke signals with guns waiting behind points of concealment.',
'Group of females begging help, but turn out to be armed or disguised.',
'Abandoned trade caravan filled with hidden raiders.',
'Dead monster carcass with predators hidden about.',
'Supplies or something provocative with a snare or net set nearby.',
'Radio distress signal broadcast by an apparatus rigged to blow.',
'A small ruin rigged to collapse and trap the party inside.',
'Monster setting up an appealing lure to draw party into its mouth.',
'Civilians taken hostage to negotiate relinquishment of supplies.',
'Looted supply crates with enemies buried in the ground round about.',
'Enemies ready to dislodge falling debris on a slope.',
'Food in a cave that has hidden pitfalls set to capture the party.',
'Abandoned trade caravan filled with hidden vermin.',
'Wounded person calls for help with his/her attackers waiting nearby.',
'A straggler begs for assistance and robs the party when they sleep.',
'A straggler begs for assistance and leads the party into an ambush.',
'Another group offers trade, but sells defective items.',
'Another group offers to give directions, but misdirects and attacks later.',
'Device set to stun party so they may be captured by slavers.'
]

