gen_data["Italian_male_common"] = [
'Andrea', 'Antonio', 'Bartolomeo', 'Bernardo', 'Bonacorso', 'Francesco', 'Gherardo', 'Giovanni', 'Guido', 'Iacopo', 'Piero', 'Ugo'
]
gen_data["Italian_male_uncommon"] = [
'Agnello', 'Agostino', 'Aiuto', 'Alamanno', 'Albergo', 'Alberto', 'Albizzo', 'Alcherio', 'Alessandro', 'Alesso', 'Alfieri', 'Alfonso', 'Aliotto', 'Amannato', 'Amato', 'Amerigo', 'Amico', 'Andrea', 'Angelo', 'Angiolo', 'Anselmo', 'Antonio', 'Ardovino', 'Argometto', 'Arnolda', 'Arnolfo', 'Arrigo', 'Attaviano', 'Averardo', 'Azzo', 'Baldanza', 'Baldassare', 'Baldino', 'Baldovino', 'Bandino', 'Bando', 'Barduccio', 'Barone', 'Bartolomeo', 'Bastiano', 'Battista', 'Beccio', 'Bellomo', 'Bencivenni', 'Bene', 'Benecto', 'Benedetto', 'Benenato', 'Benincasa', 'Benintende', 'Benivieni', 'Benvenuto', 'Bergo', 'Bernardino', 'Bernardo', 'Bernecto', 'Bertoldo', 'Bianco', 'Bifolco', 'Boccaccio', 'Bolgarino', 'Bonacolto', 'Bonacorso', 'Bonafide', 'Bonagionta', 'Bonaguida', 'Bonaiuto', 'Bonamico', 'Bonaventura', 'Bondia', 'Bonfigliolo', 'Bonifazio', 'Boninsegna', 'Bono', 'Bonvesin', 'Borghino', 'Brancazio', 'Brunaccio', 'Brunetto', 'Buonasera', 'Buonavere', 'Buongratia', 'Calcisciano', 'Cambio', 'Carlo', 'Caroccio', 'Castello', 'Cecco', 'Chiaro', 'Cittadino', 'Compagno', 'Conte', 'Corso', 'Cristiano', 'Cristofano', 'Damiano', 'Dato', 'Davino', 'Diedato', 'Dietisalvi', 'Domenico', 'Donato', 'Enzio', 'Fabiano', 'Falcone', 'Felice', 'Ferrante', 'Filippo', 'Folco', 'Forese', 'Fortis', 'Francardo', 'Francesco', 'Franco', 'Frediano', 'Froderico', 'Fruosino', 'Gabbriello', 'Galeotto', 'Galgano', 'Gherardo', 'Ghiandolfino', 'Ghino', 'Gianni', 'Giordano', 'Giotto', 'Giovanni', 'Giovenco', 'Giraldo', 'Gismondo', 'Gottifredi', 'Grano', 'Gratiano', 'Gregorio', 'Grugno', 'Gualando', 'Gualteri', 'Guantino', 'Guidaccio', 'Guido', 'Guilelmo', 'Guiliano', 'Guiscardo', 'Iacopo', 'Ildebrando', 'Lamberto', 'Lando', 'Lanfranco', 'Leolo', 'Leonardo', 'Lodovico', 'Lorenzo', 'Lucchese', 'Lupardo', 'Lutterio', 'Manfredi', 'Manno', 'Marchionne', 'Marco', 'Marignano', 'Mariotto', 'Marsilio', 'Martino', 'Marzocco', 'Matteo', 'Mazzeo', 'Melanese', 'Melliorato', 'Melliore', 'Mercato', 'Michele', 'Montanino', 'Muricone', 'Nastagio', 'Negozante', 'Nero', 'Niccolo', 'Nofri', 'Oddo', 'Odimondo', 'Oliverio', 'Omodeo', 'Opizo', 'Orlando', 'Ormanno', 'Orsino', 'Pace', 'Paganino', 'Palmieri', 'Pandolfo', 'Paolo', 'Pazzino', 'Pellario', 'Pellegrino', 'Perfetto', 'Pericciolo', 'Pero', 'Piero', 'Pierozzo', 'Pierpaolo', 'Pisano', 'Raffaello', 'Ramondo', 'Ranero', 'Ranuccio', 'Riccardo', 'Ricco', 'Ridolfo', 'Rinaldo', 'Rinieri', 'Romeo', 'Rosso', 'Ruberto', 'Ruggieri', 'Rustico', 'Sabbatino', 'Salvestro', 'Salvi', 'Silvestro', 'Simone', 'Sinibaldo', 'Sismondo', 'Sordello', 'Stefano', 'Strozza', 'Taddeo', 'Talento', 'Tancredi', 'Tedice', 'Tingoso', 'Tomaso', 'Tuccio', 'Turco', 'Ubaldino', 'Ubaldo', 'Ubertino', 'Uberto', 'Ugo', 'Ugolino', 'Ulfilas', 'Upizino', 'Vecchio', 'Ventura', 'Vernaccio', 'Vieri', 'Villano', 'Vincenzo', 'Vitale', 'Viviano'
]
gen_data["Italian_female_common"] = [
'Amata', 'Antonia', 'Benvenuta', 'Berta', 'Bona', 'Bruna', 'Clara', 'Flore', 'Letitia', 'Massaria', 'Rosana', 'Verde'
]
gen_data["Italian_female_uncommon"] = [
'Aconçata', 'Adelagia', 'Adelasia', 'Adeleta', 'Agnese', 'Agnola', 'Agustola', 'Aighina', 'Alamanna', 'Albagia', 'Albina', 'Albissima', 'Alda', 'Aldiana', 'Aldrovandina', 'Alessandra', 'Altadonna', 'Altafesta', 'Alumenata', 'Amata', 'Andreola', 'Anfiliga', 'Angela', 'Anguilutia', 'Antonia', 'Apregiata', 'Armilia', 'Auria', 'Aveduta', 'Ayguana', 'Balsama', 'Bandecca', 'Barsia', 'Bartholomea', 'Beatrix', 'Bectonesa', 'Belafanta', 'Belda', 'Beldina', 'Bella', 'Bellavedere', 'Bellavene', 'Benadacta', 'Benassaie', 'Bencevene', 'Benguardata', 'Benvenuta', 'Berarda', 'Bernardina', 'Berta', 'Bice', 'Bisantia', 'Bisciolenda', 'Boccia', 'Bolia', 'Bona', 'Bonabella', 'Bonadomane', 'Bonagratia', 'Bonasia', 'Bonaventura', 'Bondina', 'Bonola', 'Bruna', 'Brunella', 'Caramanna', 'Carlutia', 'Çasmundina', 'Casola', 'Castellana', 'Caterina', 'Çausita', 'Cavoneria', 'Cecca', 'Cicilia', 'Clara', 'Clarastella', 'Comitissa', 'Complitola', 'Conçata', 'Conciata', 'Consilieria', 'Consola', 'Contegiana', 'Coppola', 'Corbella', 'Cortese', 'Crescembene', 'Cuniza', 'Damocta', 'Daria', 'Demorola', 'Dialdana', 'Dialta', 'Diamante', 'Diana', 'Divitia', 'Dolce', 'Domnula', 'Donnessa', 'Drosa', 'Druda', 'Drudola', 'Egidia', 'Elemosina', 'Elizabeth', 'Encresciuta', 'Fabressa', 'Falconeria', 'Fiametta', 'Filippa', 'Flora', 'Florita', 'Francesca', 'Franceschina', 'Gaita', 'Galitia', 'Gaudente', 'Gelentesa', 'Gemma', 'Genevria', 'Genna', 'Giana', 'Gianetta', 'Gilia', 'Ginevria', 'Giovanna', 'Gratia', 'Grimelda', 'Grisanda', 'Guarnita', 'Guerreria', 'Guinelda', 'Gulielmina', 'Honestola', 'Iacoba', 'Iacomina', 'Iaquinta', 'Imilia', 'Inglorida', 'Ingrada', 'Iohanna', 'Isabetta', 'Isotta', 'Iulia', 'Iuliana', 'Lacosciana', 'Leta', 'Letitia', 'Lisa', 'Lorita', 'Lucia', 'Lucrezia', 'Lukesa', 'Mabilia', 'Madolina', 'Maralda', 'Marçolina', 'Marcutia', 'Margarita', 'Margola', 'Maria', 'Maridonna', 'Marina', 'Marozia', 'Marsilia', 'Martina', 'Massaria', 'Matabruna', 'Matelda', 'Mathea', 'Medonia', 'Meldina', 'Meliorata', 'Meliore', 'Midonia', 'Montanaria', 'Munaldescha', 'Muriel', 'Nanna', 'Nicola', 'Niccolosa', 'Nobilis', 'Odierna', 'Orabella', 'Orabilis', 'Oradina', 'Orlandina', 'Palma', 'Palmeria', 'Paula', 'Paulina', 'Pelegrina', 'Pera', 'Perusina', 'Pia', 'Piera', 'Placevele', 'Plana', 'Pleneria', 'Pocobella', 'Prima', 'Puçarella', 'Puçola', 'Ranutia', 'Regina', 'Riccia', 'Romana', 'Rosa', 'Rosana', 'Rosanella', 'Rustica', 'Sabatina', 'Salomia', 'Sanda', 'Santesa', 'Scarlata', 'Selanda', 'Serena', 'Setembrina', 'Sibilia', 'Sifa', 'Simonecta', 'Sovrana', 'Stefania', 'Tadea', 'Talia', 'Tedescha', 'Theodora', 'Ticta', 'Tomasia', 'Tullia', 'Ugolina', 'Verde', 'Verdelanda', 'Verderia', 'Verdiana', 'Verdis', 'Vermilia', 'Verona', 'Veronica', 'Versilia', 'Vicina', 'Virdiana', 'Viridis', 'Vita', 'Vivola', 'Yça', 'Ymilia', 'Ysabella'
]

gen_data["Italian_male_name"] = {
    '1-80': '{Italian_male_common}',
    '81-100': '{Italian_male_uncommon}'
}
gen_data["Italian_female_name"] = {
    '1-80': '{Italian_female_common}',
    '81-100': '{Italian_female_uncommon}'
}
