
/*
TODO: Get this correct with all the different naming standards from Wikipedia.  This will work for now

*/
gen_data['names'] = [
	'{roman_last_names}',
	'{roman_last_names}',
	'{roman_last_names}',
	'{roman_last_names}',
	'{roman_last_names}',
	'{roman_female_names} {roman_last_names}',
	'{roman_male_names} {roman_last_names}',
	'{roman_female_names} {roman_last_names} of {roman_city_names}',
	'{roman_male_names} {roman_last_names} of {roman_city_names}',
	'{roman_female_names} {roman_last_names} {roman_female_names} of {roman_city_names}',
	'{roman_male_names} {roman_last_names} {roman_male_names} of {roman_city_names}'
]

gen_data['roman_city_names'] = [
	'{roman_city_names_short}',
	'{roman_city_names_short}',
	'{roman_city_names_short}',
	'{roman_city_names_short}',
	'{roman_city_names_and_providences}'
]

gen_data['roman_city_names_short'] = [
'Arsinoe',
'Latopolis',
'Raphae',
'Syene',
'Tentyra',
'Bagradas',
'Capsa',
'Carthago',
'Cillium',
'Clupea',
'Hippo Regius',
'Madauros',
'Rusicade',
'Saldae',
'Tupusuctu',
'Oea',
'Ptolemais',
'Sabratha',
'Sicca Veneria',
'Simitthu',
'Sufetula',
'Taparura',
'Thugga',
'Thysdrus',
'Bosona',
'Aballava',
'Aesica',
'Anderida',
'Aquae Sulis',
'Arbeia',
'Bremetennacum Veteranorum',
'Burrium',
'Caledonia',
'Calleva Atrebatum',
'Cambria',
'Camulodunum',
'Cantabrigia',
'Cataractonium',
'Cilurnum',
'Coria',
'Corinium',
'Coristopitum',
'Corvinium',
'Cunetio',
'Danum',
'Derventio',
'Deva',
'Dubris',
'Durnovaria',
'Durovernum Cantiacorum',
'Eburacum',
'Gariannonum',
'Glannaventa',
'Glevum',
'Isca Dumnoniorum',
'Isca',
'Isurium',
'Lavatrae',
'Legentium',
'Letocetum',
'Leucarum',
'Lindinis',
'Lindum',
'Londinium',
'Luguvalium',
'Mamucium',
'Moridunum',
'Nervia Glevensium',
'Nidum',
'Noviomagus',
'Olicana',
'Pons Aelius',
'Pontus Fractus',
'Portus Adurni',
'Ratea Colitanorum',
'Ratae Coritanorum',
'Regulbium',
'Rutupiae',
'Segontium',
'Trimontium',
'Venta Belgarum',
'Venta Silurum',
'Vernementum',
'Verulamium',
'Vindomora',
'Vinovia',
'Vinovium',
'Viroconium Cornoviorum',
'Hibernia',
'Danaster',
'Raetinium',
'Mursa',
'Parentium',
'Pharos',
'Pola',
'Salonae',
'Siscia',
'Spalatum',
'Risinium',
'Adana',
'Adramyttium',
'Aenus',
'Amida',
'Acyra',
'Antioch',
'Apamea',
'Aphrodisias',
'Arcadiopolis',
'Bergula',
'Bisanthe',
'Byzantium',
'Caenophrurium',
'Caesarea Mazaca',
'Celaenae',
'Chalcedon',
'Chrysopolis',
'Constantinopolis',
'Hadrianopolis',
'Heraclea',
'Mazaca',
'Melitene',
'Perinthus',
'Rhaedestus',
'Selymbria',
'Sinope',
'Trapezus',
'Trebizond',
'Xanthus',
'Zama Regia',
'Zela',
'Zeugma',
'Aballo',
'Aballum',
'Agathe',
'Agedincum',
'Ambiani',
'Anicium',
'Antipolis',
'Aquae Sextiae',
'Aquitania',
'Aquis Voconis',
'Arausio',
'Arelate',
'Argentoratum',
'Armorica',
'Arverni',
'Atrebatum',
'Augusta Trebecorum',
'Augustobona',
'Augustodunum',
'Augustonementum',
'Aurelia',
'Aurelianum',
'Autricum',
'Avennio',
'Baeterrae',
'Bononia',
'Brivas',
'Burdigala',
'Caesarodunum',
'Campi Catalaunii',
'Carcaso',
'Carnotum',
'Cenabum Aureliani',
'Cenebelum',
'Condate Redones',
'Constantia',
'Coriallum',
'Corisopitum',
'Cularo',
'Duranius',
'Durocorotum',
'Garumna',
'Gesoriacum',
'Gratianopolis',
'Isara',
'Liger',
'Limonum',
'Lugdunum',
'Lutetia Parisiorum',
'Massilia',
'Mediolanum Aulercorum',
'Mediolanum Santonum',
'Metis',
'Narbo',
'Nemausus',
'Nevirnum',
'Noviodunum Aeduorum',
'Novioritum',
'Podium Aniciense',
'Portus',
'Portus Itius',
'Rotomagus',
'Samarobriva',
'Senones',
'Turnacum Nerviorum',
'Ugernum',
'Valentia',
'Vesunna',
'Vezeliacum',
'Vienna',
'Vizeliacum',
'Aquae Helveticae',
'Augusta Raurica',
'Aventicum',
'Curia',
'Dunum',
'Eburodunum',
'Forum Claudii Vallensium',
'Geneva',
'Novodunum',
'Octodurus',
'Tigurum',
'Turicim',
'Vindonissa',
'Vitudurum',
'Rhodanos',
'Rhenus',
'Atuatuca Tungrorum',
'Belgica',
'Cortoriacum',
'Gandava',
'Abudiacum',
'Abusina',
'Aquisgranium',
'Augusta Trevirorum',
'Augusta Vindelicorum',
'Aurelia Aquensi',
'Batavis',
'Belginum',
'Bona',
'Castellum apud Confluentes',
'Castra Batavorum',
'Castra Regina',
'Colonia Agrippina(e)',
'Colonia Agrippinensium',
'Colonia Ulpia Traiana',
'Constantia',
'Blariacum',
'Castellum Flevum',
'Coriovallum',
'Germania',
'Moenum',
'Moguntiacum',
'Noviomagus',
'Rigomagus',
'Sorviodurum',
'Treviri',
'Vetera',
'Vicus Belginum',
'Forum Hadriani',
'Haga-Comitis',
'Lugdunum Batavorum',
'Noviomagus Batavodurum',
'Praetorium Agrippinae',
'Traiectum ad Mosam',
'Traiectum Eriditum',
'Ulpia Novomagus',
'Ambracia',
'Athenae',
'Corcyra',
'Abdera',
'Abula',
'Acci',
'Acinipo',
'Asturica',
'Augusta Emerita',
'Baeloe',
'Baetulo',
'Barcino',
'Basti',
'Bilbilis',
'Bilbilis Italica',
'Brigantium',
'Caesaraugusta',
'Calagurris',
'Calagurris Iulia Nasica',
'Caprera',
'Carmo',
'Carmona',
'Carteia',
'Carthago Nova',
'Cascantum',
'Castrum Octavianum',
'Castulo',
'Cauca',
'Celsa',
'Clunia',
'Colonia Augusta Emerita',
'Colonia Baelo Claudia',
'Colonia Caecilia Metellinum',
'Colonia Caesar Augusta',
'Colonia Iulia Gemella Acci',
'Colonia Iulia Illici Augusta',
'Colonia Iulia Romula',
'Colonia Norba Caesarina',
'Colonia Patricia',
'Colonia Victrix Iulia Celsa',
'Colonia Victrix Iulia Lepida',
'Complutum',
'Corduba',
'Dertosa',
'Dianinum',
'Ebrus',
'Egara',
'Emerita',
'Emporiae',
'Gades',
'Graccurris',
'Hispalis',
'Ilerda',
'Illici',
'Italica',
'Iulia Traducta',
'Lascuta',
'Legio',
'Lucentum',
'Lucus Augusti',
'Malaca',
'Metellinum',
'Municipium Augusta Bilbilis',
'Norba',
'Numantia',
'Obulco',
'Onuba',
'Osca',
'Osset',
'Pompaelo',
'Saguntum',
'Salmantica',
'Segobriga',
'Segovia',
'Tarraco',
'Toletum',
'Turiaso',
'Turiaso Silbis',
'Urbs Victrix Osca',
'Valentia Edetanorum',
'Iberia',
'Budalia',
'Malata Bonenia',
'Naissus',
'Singidunum',
'Sirmium',
'Viminiacum',
'Ad Novas',
'Ader',
'Aqua Viva',
'Cibalae',
'Aemona',
'Atrans',
'Celeia',
'Dimale',
'Dyrrachium',
'Epidamnus',
'Emona',
'Labacum',
'Neviodunum',
'Poetovio',
'Praetorium Latobicorum',
'Acrae',
'Aesernia',
'Agrigentum',
'Albanum',
'Anio',
'Antium',
'Aquae Cutiliae',
'Aquileia',
'Ariminium',
'Asisium',
'Augusta Praetoria',
'Augusta Taurinorum',
'Baiae',
'Barium',
'Bedriacum',
'Beneventum',
'Bergomum',
'Bononia',
'Brixellum',
'Brundisium',
'Caesena',
'Carales',
'Cannae',
'Canusum',
'Caprae',
'Clusium',
'Comum',
'Concordia Sagittaria',
'Dertona',
'Drepana',
'Drepanum',
'Ecnomus',
'Eryx',
'Faesulae',
'Florentia',
'Forum Iulii',
'Iulia Concordia',
'Liburnum',
'Lilybaeum',
'Mediolanum',
'Messana',
'Misenum',
'Mons Bellona',
'Mutina',
'Neapolis',
'Nola',
'Opitergium',
'Padus',
'Panormus',
'Patavium',
'Perusia',
'Pisae',
'Placentia',
'Pompeii',
'Puteoli',
'Ravenna',
'Rhegium',
'Roma',
'Segusio',
'Spoletium',
'Syracusae',
'Tarentum',
'Tarvisium',
'Taurinum',
'Tergeste',
'Ticinum',
'Tridentum',
'Utinum',
'Venetiae',
'Vicentia',
'Ascalon',
'Bethar',
'Caesarea Maritima',
'Aelia Capitolina',
'Berytus',
'Byblus',
'Adraa',
'Apamea',
'Bostra',
'Canatha',
'Hierosolyma',
'Gerasa',
'Philadelphia',
'Heliopolis',
'Tripolis',
'Tyrus',
'Aeminium',
'Bracara Augusta',
'Conimbriga',
'Lusitania',
'Olisipo',
'Ossonoba',
'Pax Iulia',
'Portus Cale',
'Apollonia',
'Colonia Flavia Scupi',
'Heraclea Lyncestis',
'Lihnidos',
'Scupi',
'Stobi',
'Magador',
'Tingi',
'Carrhae',
'Circesium',
'Pumbedita',
'Sippar',
'Caesarea',
'Calceus Herculis',
'Cartennae',
'Chullu',
'Cirta',
'Cuicul',
'Ad Anisum',
'Ad Iuvense',
'Ad Mauros',
'Aelium Cetium',
'Aequinoctium',
'Aguntum',
'Ala Nova',
'Arelape',
'Augustianis',
'Cannabiaca',
'Brigantium',
'Carnuntum',
'Comagena',
'Danuvius',
'Ad Flexum',
'Ad Statuas',
'Ad Statuas',
'Altinum',
'Aquincum',
'Arrabona',
'Bononia Malata',
'Brigetio',
'Campona',
'Castra ad Herculem',
'Cirpi',
'Colonia Claudia Savaria',
'Favianis',
'Flavia Solva',
'Ioviacum',
'Lauriacum',
'Lentia',
'Lincium',
'Oenipontum',
'Veldidena',
'Vienna',
'Vindobona',
'Istrus',
'Gorsium',
'Herculea',
'Iaurinum',
'Intercisa',
'Lugio',
'Lussonium',
'Matrica',
'Mogentianae',
'Quinque-Ecclesiis',
'Salva',
'Savaria',
'Scarbantia',
'Sempronium',
'Solva',
'Sopianae',
'Tricciana',
'Ulcisia Castra',
'Valcum',
'Gerulata',
'Istropolis',
'Posonium',
'Ad Mediam',
'Apulum',
'Arcidava',
'Berzobis',
'Callatis',
'Claudiopolis',
'Colonia Ulpia Traiana',
'Dierna',
'Drobeta',
'Histria',
'Lederata',
'Napoca',
'Potaissa',
'Sarmizegethusa',
'Sucidava',
'Tomis',
'Tropaeum Traiani',
'Varadinum',
'Rusaddir',
'Emesa',
'Palmyra',
'Resapha',
'Sergiopolis',
'Abritus',
'Abrittus',
'Almus',
'Anchialus',
'Anhialo',
'Apollonia Pontica',
'Augusta Trajana',
'Beroe Augusta Trajana',
'Bononia',
'Castra Martis',
'Dimum',
'Diocletianopolis',
'Dionysopolis',
'Durostorum',
'Marcianopolis',
'Melta',
'Messambria',
'Montana',
'Novae',
'Odessus',
'Pautalia',
'Philippopolis',
'Ratiara',
'Serdica',
'Sexaginta Prista',
'Sozopolis',
'Storgozia',
'Trimontium',
'Cyrene'
]

gen_data['roman_city_names_and_providences'] = [
'Arsinoe in the providence of Aegyptus',
'Latopolis in the providence of Aegyptus',
'Raphae in the providence of Aegyptus',
'Syene in the providence of Aegyptus',
'Tentyra in the providence of Aegyptus',
'Bagradas in the providence of Africa Proconsularis',
'Capsa in the providence of Africa Proconsularis',
'Carthago in the providence of Africa Proconsularis',
'Cillium in the providence of Africa Proconsularis',
'Clupea in the providence of Africa Proconsularis',
'Hippo Regius in the providence of Africa Proconsularis',
'Madauros in the providence of Africa Proconsularis',
'Rusicade in the providence of Africa Proconsularis',
'Saldae in the providence of Africa Proconsularis',
'Tupusuctu in the providence of Africa Proconsularis',
'Oea in the providence of Africa Proconsularis',
'Ptolemais in the providence of Africa Proconsularis',
'Sabratha in the providence of Africa Proconsularis',
'Sicca Veneria in the providence of Africa Proconsularis',
'Simitthu in the providence of Africa Proconsularis',
'Sufetula in the providence of Africa Proconsularis',
'Taparura in the providence of Africa Proconsularis',
'Thugga in the providence of Africa Proconsularis',
'Thysdrus in the providence of Africa Proconsularis',
'Bosona in the providence of Bosnia Herzegovina',
'Aballava in the providence of Britannia',
'Aesica in the providence of Britannia',
'Anderida in the providence of Britannia',
'Aquae Sulis in the providence of Britannia',
'Arbeia in the providence of Britannia',
'Bremetennacum Veteranorum in the providence of Britannia',
'Burrium in the providence of Britannia',
'Caledonia in the providence of Britannia',
'Calleva Atrebatum in the providence of Britannia',
'Cambria in the providence of Britannia',
'Camulodunum in the providence of Britannia',
'Cantabrigia in the providence of Britannia',
'Cataractonium in the providence of Britannia',
'Cilurnum in the providence of Britannia',
'Coria in the providence of Britannia',
'Corinium in the providence of Britannia',
'Coristopitum in the providence of Britannia',
'Corvinium in the providence of Britannia',
'Cunetio in the providence of Britannia',
'Danum in the providence of Britannia',
'Derventio in the providence of Britannia',
'Deva in the providence of Britannia',
'Dubris in the providence of Britannia',
'Durnovaria in the providence of Britannia',
'Durovernum Cantiacorum in the providence of Britannia',
'Eburacum in the providence of Britannia',
'Gariannonum in the providence of Britannia',
'Glannaventa in the providence of Britannia',
'Glevum in the providence of Britannia',
'Isca Dumnoniorum in the providence of Britannia',
'Isca in the providence of Britannia',
'Isurium in the providence of Britannia',
'Lavatrae in the providence of Britannia',
'Legentium in the providence of Britannia',
'Letocetum in the providence of Britannia',
'Leucarum in the providence of Britannia',
'Lindinis in the providence of Britannia',
'Lindum in the providence of Britannia',
'Londinium in the providence of Britannia',
'Luguvalium in the providence of Britannia',
'Mamucium in the providence of Britannia',
'Moridunum in the providence of Britannia',
'Nervia Glevensium in the providence of Britannia',
'Nidum in the providence of Britannia',
'Noviomagus in the providence of Britannia',
'Olicana in the providence of Britannia',
'Pons Aelius in the providence of Britannia',
'Pontus Fractus in the providence of Britannia',
'Portus Adurni in the providence of Britannia',
'Ratea Colitanorum in the providence of Britannia',
'Ratae Coritanorum in the providence of Britannia',
'Regulbium in the providence of Britannia',
'Rutupiae in the providence of Britannia',
'Segontium in the providence of Britannia',
'Trimontium in the providence of Britannia',
'Venta Belgarum in the providence of Britannia',
'Venta Silurum in the providence of Britannia',
'Vernementum in the providence of Britannia',
'Verulamium in the providence of Britannia',
'Vindomora in the providence of Britannia',
'Vinovia in the providence of Britannia',
'Vinovium in the providence of Britannia',
'Viroconium Cornoviorum in the providence of Britannia',
'Hibernia in the providence of BRItannia',
'Danaster in the providence of Crimean',
'Raetinium in the providence of Dalmatia',
'Mursa in the providence of Dalmatia',
'Parentium in the providence of Dalmatia',
'Pharos in the providence of Dalmatia',
'Pola in the providence of Dalmatia',
'Salonae in the providence of Dalmatia',
'Siscia in the providence of Dalmatia',
'Spalatum in the providence of Dalmatia',
'Risinium in the providence of Dalmatia',
'Adana in the providence of Galatia',
'Adramyttium in the providence of Galatia',
'Aenus in the providence of Galatia',
'Amida in the providence of Galatia',
'Acyra in the providence of Galatia',
'Antioch in the providence of Galatia',
'Apamea in the providence of Galatia',
'Aphrodisias in the providence of Galatia',
'Arcadiopolis in the providence of Galatia',
'Bergula in the providence of Galatia',
'Bisanthe in the providence of Galatia',
'Byzantium in the providence of Galatia',
'Caenophrurium in the providence of Galatia',
'Caesarea Mazaca in the providence of Galatia',
'Celaenae in the providence of Galatia',
'Chalcedon in the providence of Galatia',
'Chrysopolis in the providence of Galatia',
'Constantinopolis in the providence of Galatia',
'Hadrianopolis in the providence of Galatia',
'Heraclea in the providence of Galatia',
'Mazaca in the providence of Galatia',
'Melitene in the providence of Galatia',
'Perinthus in the providence of Galatia',
'Rhaedestus in the providence of Galatia',
'Selymbria in the providence of Galatia',
'Sinope in the providence of Galatia',
'Trapezus in the providence of Galatia',
'Trebizond in the providence of Galatia',
'Xanthus in the providence of Galatia',
'Zama Regia in the providence of Galatia',
'Zela in the providence of Galatia',
'Zeugma in the providence of Galatia',
'Aballo in the providence of Gallia',
'Aballum in the providence of Gallia',
'Agathe in the providence of Gallia',
'Agedincum in the providence of Gallia',
'Ambiani in the providence of Gallia',
'Anicium in the providence of Gallia',
'Antipolis in the providence of Gallia',
'Aquae Sextiae in the providence of Gallia',
'Aquitania in the providence of Gallia',
'Aquis Voconis in the providence of Gallia',
'Arausio in the providence of Gallia',
'Arelate in the providence of Gallia',
'Argentoratum in the providence of Gallia',
'Armorica in the providence of Gallia',
'Arverni in the providence of Gallia',
'Atrebatum in the providence of Gallia',
'Augusta Trebecorum in the providence of Gallia',
'Augustobona in the providence of Gallia',
'Augustodunum in the providence of Gallia',
'Augustonementum in the providence of Gallia',
'Aurelia in the providence of Gallia',
'Aurelianum in the providence of Gallia',
'Autricum in the providence of Gallia',
'Avennio in the providence of Gallia',
'Baeterrae in the providence of Gallia',
'Bononia in the providence of Gallia',
'Brivas in the providence of Gallia',
'Burdigala in the providence of Gallia',
'Caesarodunum in the providence of Gallia',
'Campi Catalaunii in the providence of Gallia',
'Carcaso in the providence of Gallia',
'Carnotum in the providence of Gallia',
'Cenabum Aureliani in the providence of Gallia',
'Cenebelum in the providence of Gallia',
'Condate Redones in the providence of Gallia',
'Constantia in the providence of Gallia',
'Coriallum in the providence of Gallia',
'Corisopitum in the providence of Gallia',
'Cularo in the providence of Gallia',
'Duranius in the providence of Gallia',
'Durocorotum in the providence of Gallia',
'Garumna in the providence of Gallia',
'Gesoriacum in the providence of Gallia',
'Gratianopolis in the providence of Gallia',
'Isara in the providence of Gallia',
'Liger in the providence of Gallia',
'Limonum in the providence of Gallia',
'Lugdunum in the providence of Gallia',
'Lutetia Parisiorum in the providence of Gallia',
'Massilia in the providence of Gallia',
'Mediolanum Aulercorum in the providence of Gallia',
'Mediolanum Santonum in the providence of Gallia',
'Metis in the providence of Gallia',
'Narbo in the providence of Gallia',
'Nemausus in the providence of Gallia',
'Nevirnum in the providence of Gallia',
'Noviodunum Aeduorum in the providence of Gallia',
'Novioritum in the providence of Gallia',
'Podium Aniciense in the providence of Gallia',
'Portus in the providence of Gallia',
'Portus Itius in the providence of Gallia',
'Rotomagus in the providence of Gallia',
'Samarobriva in the providence of Gallia',
'Senones in the providence of Gallia',
'Turnacum Nerviorum in the providence of Gallia',
'Ugernum in the providence of Gallia',
'Valentia in the providence of Gallia',
'Vesunna in the providence of Gallia',
'Vezeliacum in the providence of Gallia',
'Vienna in the providence of Gallia',
'Vizeliacum in the providence of Gallia',
'Aquae Helveticae in the providence of Gallia Belgica',
'Augusta Raurica in the providence of Gallia Belgica',
'Aventicum in the providence of Gallia Belgica',
'Curia in the providence of Gallia Belgica',
'Dunum in the providence of Gallia Belgica',
'Eburodunum in the providence of Gallia Belgica',
'Forum Claudii Vallensium in the providence of Gallia Belgica',
'Geneva in the providence of Gallia Belgica',
'Novodunum in the providence of Gallia Belgica',
'Octodurus in the providence of Gallia Belgica',
'Tigurum in the providence of Gallia Belgica',
'Turicim in the providence of Gallia Belgica',
'Vindonissa in the providence of Gallia Belgica',
'Vitudurum in the providence of Gallia Belgica',
'Rhodanos in the providence of Gallia Belgica',
'Rhenus in the providence of Gallia Belgica',
'Atuatuca Tungrorum in the providence of Gallia Belgica ',
'Belgica in the providence of Gallia Belgica ',
'Cortoriacum in the providence of Gallia Belgica ',
'Gandava in the providence of Gallia Belgica ',
'Abudiacum in the providence of Germania',
'Abusina in the providence of Germania',
'Aquisgranium in the providence of Germania',
'Augusta Trevirorum in the providence of Germania',
'Augusta Vindelicorum in the providence of Germania',
'Aurelia Aquensi in the providence of Germania',
'Batavis in the providence of Germania',
'Belginum in the providence of Germania',
'Bona in the providence of Germania',
'Castellum apud Confluentes in the providence of Germania',
'Castra Batavorum in the providence of Germania',
'Castra Regina in the providence of Germania',
'Colonia Agrippina(e) in the providence of Germania',
'Colonia Agrippinensium in the providence of Germania',
'Colonia Ulpia Traiana in the providence of Germania',
'Constantia in the providence of Germania',
'Blariacum in the providence of Germania',
'Castellum Flevum in the providence of Germania',
'Coriovallum in the providence of Germania',
'Germania in the providence of Germania',
'Moenum in the providence of Germania',
'Moguntiacum in the providence of Germania',
'Noviomagus in the providence of Germania',
'Rigomagus in the providence of Germania',
'Sorviodurum in the providence of Germania',
'Treviri in the providence of Germania',
'Vetera in the providence of Germania',
'Vicus Belginum in the providence of Germania',
'Forum Hadriani in the providence of Germania',
'Haga-Comitis in the providence of Germania',
'Lugdunum Batavorum in the providence of Germania',
'Noviomagus Batavodurum in the providence of Germania',
'Praetorium Agrippinae in the providence of Germania',
'Traiectum ad Mosam in the providence of Germania',
'Traiectum Eriditum in the providence of Germania',
'Ulpia Novomagus in the providence of Germania',
'Ambracia in the providence of Graecia',
'Athenae in the providence of Graecia',
'Corcyra in the providence of Graecia',
'Abdera in the providence of Hispania',
'Abula in the providence of Hispania',
'Acci in the providence of Hispania',
'Acinipo in the providence of Hispania',
'Asturica in the providence of Hispania',
'Augusta Emerita in the providence of Hispania',
'Baeloe in the providence of Hispania',
'Baetulo in the providence of Hispania',
'Barcino in the providence of Hispania',
'Basti in the providence of Hispania',
'Bilbilis in the providence of Hispania',
'Bilbilis Italica in the providence of Hispania',
'Brigantium in the providence of Hispania',
'Caesaraugusta in the providence of Hispania',
'Calagurris in the providence of Hispania',
'Calagurris Iulia Nasica in the providence of Hispania',
'Caprera in the providence of Hispania',
'Carmo in the providence of Hispania',
'Carmona in the providence of Hispania',
'Carteia in the providence of Hispania',
'Carthago Nova in the providence of Hispania',
'Cascantum in the providence of Hispania',
'Castrum Octavianum in the providence of Hispania',
'Castulo in the providence of Hispania',
'Cauca in the providence of Hispania',
'Celsa in the providence of Hispania',
'Clunia in the providence of Hispania',
'Colonia Augusta Emerita in the providence of Hispania',
'Colonia Baelo Claudia in the providence of Hispania',
'Colonia Caecilia Metellinum in the providence of Hispania',
'Colonia Caesar Augusta in the providence of Hispania',
'Colonia Iulia Gemella Acci in the providence of Hispania',
'Colonia Iulia Illici Augusta in the providence of Hispania',
'Colonia Iulia Romula in the providence of Hispania',
'Colonia Norba Caesarina in the providence of Hispania',
'Colonia Patricia in the providence of Hispania',
'Colonia Victrix Iulia Celsa in the providence of Hispania',
'Colonia Victrix Iulia Lepida in the providence of Hispania',
'Complutum in the providence of Hispania',
'Corduba in the providence of Hispania',
'Dertosa in the providence of Hispania',
'Dianinum in the providence of Hispania',
'Ebrus in the providence of Hispania',
'Egara in the providence of Hispania',
'Emerita in the providence of Hispania',
'Emporiae in the providence of Hispania',
'Gades in the providence of Hispania',
'Graccurris in the providence of Hispania',
'Hispalis in the providence of Hispania',
'Ilerda in the providence of Hispania',
'Illici in the providence of Hispania',
'Italica in the providence of Hispania',
'Iulia Traducta in the providence of Hispania',
'Lascuta in the providence of Hispania',
'Legio in the providence of Hispania',
'Lucentum in the providence of Hispania',
'Lucus Augusti in the providence of Hispania',
'Malaca in the providence of Hispania',
'Metellinum in the providence of Hispania',
'Municipium Augusta Bilbilis in the providence of Hispania',
'Norba in the providence of Hispania',
'Numantia in the providence of Hispania',
'Obulco in the providence of Hispania',
'Onuba in the providence of Hispania',
'Osca in the providence of Hispania',
'Osset in the providence of Hispania',
'Pompaelo in the providence of Hispania',
'Saguntum in the providence of Hispania',
'Salmantica in the providence of Hispania',
'Segobriga in the providence of Hispania',
'Segovia in the providence of Hispania',
'Tarraco in the providence of Hispania',
'Toletum in the providence of Hispania',
'Turiaso in the providence of Hispania',
'Turiaso Silbis in the providence of Hispania',
'Urbs Victrix Osca in the providence of Hispania',
'Valentia Edetanorum in the providence of Hispania',
'Iberia in the providence of Hispania',
'Budalia in the providence of Illyria',
'Malata Bonenia in the providence of Illyria',
'Naissus in the providence of Illyria',
'Singidunum in the providence of Illyria',
'Sirmium in the providence of Illyria',
'Viminiacum in the providence of Illyria',
'Ad Novas in the providence of Illyricum',
'Ader in the providence of Illyricum',
'Aqua Viva in the providence of Illyricum',
'Cibalae in the providence of Illyricum',
'Aemona in the providence of Illyricum',
'Atrans in the providence of Illyricum',
'Celeia in the providence of Illyricum',
'Dimale in the providence of Illyricum',
'Dyrrachium in the providence of Illyricum',
'Epidamnus in the providence of Illyricum',
'Emona in the providence of Illyricum',
'Labacum in the providence of Illyricum',
'Neviodunum in the providence of Illyricum',
'Poetovio in the providence of Illyricum',
'Praetorium Latobicorum in the providence of Illyricum',
'Acrae in the providence of Italia',
'Aesernia in the providence of Italia',
'Agrigentum in the providence of Italia',
'Albanum in the providence of Italia',
'Anio in the providence of Italia',
'Antium in the providence of Italia',
'Aquae Cutiliae in the providence of Italia',
'Aquileia in the providence of Italia',
'Ariminium in the providence of Italia',
'Asisium in the providence of Italia',
'Augusta Praetoria in the providence of Italia',
'Augusta Taurinorum in the providence of Italia',
'Baiae in the providence of Italia',
'Barium in the providence of Italia',
'Bedriacum in the providence of Italia',
'Beneventum in the providence of Italia',
'Bergomum in the providence of Italia',
'Bononia in the providence of Italia',
'Brixellum in the providence of Italia',
'Brundisium in the providence of Italia',
'Caesena in the providence of Italia',
'Carales in the providence of Italia',
'Cannae in the providence of Italia',
'Canusum in the providence of Italia',
'Caprae in the providence of Italia',
'Clusium in the providence of Italia',
'Comum in the providence of Italia',
'Concordia Sagittaria in the providence of Italia',
'Dertona in the providence of Italia',
'Drepana in the providence of Italia',
'Drepanum in the providence of Italia',
'Ecnomus in the providence of Italia',
'Eryx in the providence of Italia',
'Faesulae in the providence of Italia',
'Florentia in the providence of Italia',
'Forum Iulii in the providence of Italia',
'Iulia Concordia in the providence of Italia',
'Liburnum in the providence of Italia',
'Lilybaeum in the providence of Italia',
'Mediolanum in the providence of Italia',
'Messana in the providence of Italia',
'Misenum in the providence of Italia',
'Mons Bellona in the providence of Italia',
'Mutina in the providence of Italia',
'Neapolis in the providence of Italia',
'Nola in the providence of Italia',
'Opitergium in the providence of Italia',
'Padus in the providence of Italia',
'Panormus in the providence of Italia',
'Patavium in the providence of Italia',
'Perusia in the providence of Italia',
'Pisae in the providence of Italia',
'Placentia in the providence of Italia',
'Pompeii in the providence of Italia',
'Puteoli in the providence of Italia',
'Ravenna in the providence of Italia',
'Rhegium in the providence of Italia',
'Roma in the providence of Italia',
'Segusio in the providence of Italia',
'Spoletium in the providence of Italia',
'Syracusae in the providence of Italia',
'Tarentum in the providence of Italia',
'Tarvisium in the providence of Italia',
'Taurinum in the providence of Italia',
'Tergeste in the providence of Italia',
'Ticinum in the providence of Italia',
'Tridentum in the providence of Italia',
'Utinum in the providence of Italia',
'Venetiae in the providence of Italia',
'Vicentia in the providence of Italia',
'Ascalon in the providence of Judea',
'Bethar in the providence of Judea',
'Caesarea Maritima in the providence of Judea',
'Aelia Capitolina in the providence of Judea',
'Berytus in the providence of Judea',
'Byblus in the providence of Judea',
'Adraa in the providence of Judea',
'Apamea in the providence of Judea',
'Bostra in the providence of Judea',
'Canatha in the providence of Judea',
'Hierosolyma in the providence of JUDEA',
'Gerasa in the providence of JUDEA',
'Philadelphia in the providence of JUDEA',
'Heliopolis in the providence of JUDEA',
'Tripolis in the providence of JUDEA',
'Tyrus in the providence of JUDEA',
'Aeminium in the providence of Lusitania',
'Bracara Augusta in the providence of Lusitania',
'Conimbriga in the providence of Lusitania',
'Lusitania in the providence of Lusitania',
'Olisipo in the providence of Lusitania',
'Ossonoba in the providence of Lusitania',
'Pax Iulia in the providence of Lusitania',
'Portus Cale in the providence of Lusitania',
'Apollonia in the providence of Macedonia',
'Colonia Flavia Scupi in the providence of Macedonia',
'Heraclea Lyncestis in the providence of Macedonia',
'Lihnidos in the providence of Macedonia',
'Scupi in the providence of Macedonia',
'Stobi in the providence of Macedonia',
'Magador in the providence of Mauretania Tingitana',
'Tingi in the providence of Mauretania Tingitana',
'Carrhae in the providence of Mesopotamia',
'Circesium in the providence of Mesopotamia',
'Pumbedita in the providence of Mesopotamia',
'Sippar in the providence of Mesopotamia',
'Caesarea in the providence of Numidia',
'Calceus Herculis in the providence of Numidia',
'Cartennae in the providence of Numidia',
'Chullu in the providence of Numidia',
'Cirta in the providence of Numidia',
'Cuicul in the providence of Numidia',
'Ad Anisum in the providence of Pannonia',
'Ad Iuvense in the providence of Pannonia',
'Ad Mauros in the providence of Pannonia',
'Aelium Cetium in the providence of Pannonia',
'Aequinoctium in the providence of Pannonia',
'Aguntum in the providence of Pannonia',
'Ala Nova in the providence of Pannonia',
'Arelape in the providence of Pannonia',
'Augustianis in the providence of Pannonia',
'Cannabiaca in the providence of Pannonia',
'Brigantium in the providence of Pannonia',
'Carnuntum in the providence of Pannonia',
'Comagena in the providence of Pannonia',
'Danuvius in the providence of Pannonia',
'Ad Flexum in the providence of Pannonia',
'Ad Statuas in the providence of Pannonia',
'Ad Statuas in the providence of Pannonia',
'Altinum in the providence of Pannonia',
'Aquincum in the providence of Pannonia',
'Arrabona in the providence of Pannonia',
'Bononia Malata in the providence of Pannonia',
'Brigetio in the providence of Pannonia',
'Campona in the providence of Pannonia',
'Castra ad Herculem in the providence of Pannonia',
'Cirpi in the providence of Pannonia',
'Colonia Claudia Savaria in the providence of Pannonia',
'Favianis in the providence of Pannonia',
'Flavia Solva in the providence of Pannonia',
'Ioviacum in the providence of Pannonia',
'Lauriacum in the providence of Pannonia',
'Lentia in the providence of Pannonia',
'Lincium in the providence of Pannonia',
'Oenipontum in the providence of Pannonia',
'Veldidena in the providence of Pannonia',
'Vienna in the providence of Pannonia',
'Vindobona in the providence of Pannonia',
'Istrus in the providence of Pannonia',
'Gorsium in the providence of Pannonia',
'Herculea in the providence of Pannonia',
'Iaurinum in the providence of Pannonia',
'Intercisa in the providence of Pannonia',
'Lugio in the providence of Pannonia',
'Lussonium in the providence of Pannonia',
'Matrica in the providence of Pannonia',
'Mogentianae in the providence of Pannonia',
'Quinque-Ecclesiis in the providence of Pannonia',
'Salva in the providence of Pannonia',
'Savaria in the providence of Pannonia',
'Scarbantia in the providence of Pannonia',
'Sempronium in the providence of Pannonia',
'Solva in the providence of Pannonia',
'Sopianae in the providence of Pannonia',
'Tricciana in the providence of Pannonia',
'Ulcisia Castra in the providence of Pannonia',
'Valcum in the providence of Pannonia',
'Gerulata in the providence of Pannonia',
'Istropolis in the providence of Pannonia',
'Posonium in the providence of Pannonia',
'Ad Mediam in the providence of Roman Dacia',
'Apulum in the providence of Roman Dacia',
'Arcidava in the providence of Roman Dacia',
'Berzobis in the providence of Roman Dacia',
'Callatis in the providence of Roman Dacia',
'Claudiopolis in the providence of Roman Dacia',
'Colonia Ulpia Traiana in the providence of Roman Dacia',
'Dierna in the providence of Roman Dacia',
'Drobeta in the providence of Roman Dacia',
'Histria in the providence of Roman Dacia',
'Lederata in the providence of Roman Dacia',
'Napoca in the providence of Roman Dacia',
'Potaissa in the providence of Roman Dacia',
'Sarmizegethusa in the providence of Roman Dacia',
'Sucidava in the providence of Roman Dacia',
'Tomis in the providence of Roman Dacia',
'Tropaeum Traiani in the providence of Roman Dacia',
'Varadinum in the providence of Roman Dacia',
'Rusaddir in the providence of Spanish Mauretania',
'Emesa in the providence of Syria',
'Palmyra in the providence of Syria',
'Resapha in the providence of Syria',
'Sergiopolis in the providence of Syria',
'Abritus in the providence of Thrace',
'Abrittus in the providence of Thrace',
'Almus in the providence of Thrace',
'Anchialus in the providence of Thrace',
'Anhialo in the providence of Thrace',
'Apollonia Pontica in the providence of Thrace',
'Augusta Trajana in the providence of Thrace',
'Beroe Augusta Trajana in the providence of Thrace',
'Bononia in the providence of Thrace',
'Castra Martis in the providence of Thrace',
'Dimum in the providence of Thrace',
'Diocletianopolis in the providence of Thrace',
'Dionysopolis in the providence of Thrace',
'Durostorum in the providence of Thrace',
'Marcianopolis in the providence of Thrace',
'Melta in the providence of Thrace',
'Messambria in the providence of Thrace',
'Montana in the providence of Thrace',
'Novae in the providence of Thrace',
'Odessus in the providence of Thrace',
'Pautalia in the providence of Thrace',
'Philippopolis in the providence of Thrace',
'Ratiara in the providence of Thrace',
'Serdica in the providence of Thrace',
'Sexaginta Prista in the providence of Thrace',
'Sozopolis in the providence of Thrace',
'Storgozia in the providence of Thrace',
'Trimontium in the providence of Thrace',
'Cyrene in the providence of Tripolitania'
]


gen_data['roman_last_names'] = [
'Aburius',
'Accius',
'Accoleius',
'Acilius',
'Aebutius',
'Aedinius',
'Aelius',
'Aemilius',
'Albanius',
'Albatius',
'Allectius',
'Amatius',
'Annius',
'Antistius',
'Antius',
'Antonius',
'Appuleius',
'Aquillius',
'Armenius',
'Arrius',
'Arsinius',
'Artorius',
'Asinius',
'Ateius',
'Atius',
'Atilius',
'Atrius',
'Atronius',
'Attius',
'Aufidius',
'Aurelius',
'Aurius',
'Ausonius',
'Avidius',
'Avitus',
'Axius',
'Babudius',
'Baebius',
'Balventius',
'Bantius',
'Barbatius',
'Barrius',
'Betilienus',
'Betucius',
'Blandius',
'Blossius',
'Bruccius',
'Bruttius',
'Bucculeius',
'Burrienus',
'Caecilius',
'Caecina',
'Caecius',
'Caedicius',
'Caelius',
'Caeparius',
'Caepasius',
'Caerellius',
'Caesennius',
'Caesetius',
'Caesius',
'Caesonius',
'Caesulenus',
'Caetronius',
'Calavius',
'Calidius',
'Calpurnius',
'Calventius',
'Calvisius',
'Camilius',
'Camillius',
'Camelius',
'Canidius',
'Caninius',
'Canius',
'Cantilius',
'Cantius',
'Canuleius',
'Canutius',
'Caprenius',
'Carius',
'Caristanius',
'Carvilius',
'Cassius',
'Ceionius',
'Cicereius',
'Cilnius',
'Cincius',
'Cispius',
'Claudius',
'Clodius',
'Cloelius',
'Clovius',
'Cluilius',
'Cluntius',
'Cocceius',
'Coiedius',
'Cominius',
'Consentius',
'Considius',
'Coruncanius',
'Cordius',
'Cornelius',
'Cosconius',
'Curius',
'Curtius',
'Decumius',
'Desticius',
'Dexsius',
'Didius',
'Dillius',
'Domitius',
'Duccius',
'Duronius',
'Egnatius',
'Epidius',
'Equitius',
'Fabius',
'Fadius',
'Faenius',
'Falerius',
'Favonius',
'Festinius',
'Flavius',
'Flavinius',
'Flavonius',
'Floridius',
'Florius',
'Floronius',
'Fufius',
'Fulcinius',
'Fulvius',
'Fundanus',
'Furius',
'Gabinius',
'Galerius',
'Gavius',
'Geganius',
'Gellius',
'Granius',
'Gratius',
'Gratidius',
'Helvetius',
'Helvius',
'Herennius',
'Herminius',
'Hirtius',
'Horatius',
'Hortensius',
'Hosidius',
'Hostilius',
'Icilius',
'Insteius',
'Julius',
'Junius',
'Juventius',
'Laberius',
'Labienus',
'Laelius',
'Laetorius',
'Lafrenius',
'Lampronius',
'Lartius',
'Liburnius',
'Licinius',
'Livius',
'Lollius',
'Longinius',
'Loreius',
'Lucceius',
'Lucilius',
'Lucius',
'Lucretius',
'Lusius',
'Lutatius',
'Macrinius',
'Maecilius',
'Maelius',
'Mallius',
'Mamilius',
'Manlius',
'Manilius',
'Marcius',
'Marius',
'Matius',
'Maximius',
'Memmius',
'Menenius',
'Messienus',
'Metilius',
'Milonius',
'Minicius',
'Minucius',
'Modius',
'Mucius',
'Munatius',
'Munius',
'Murrius',
'Naevius',
'Nasennius',
'Nemetorius',
'Nepius',
'Nigidius',
'Nigilius',
'Ninnius',
'Nipius',
'Norbanus',
'Novius',
'Numerius',
'Octavius',
'Olcinius',
'Oppius',
'Opsius',
'Oranius',
'Otacilius',
'Palpellius',
'Papinius',
'Papirius',
'Papius',
'Pedius',
'Peltrasius',
'Pescennius',
'Petellius',
'Petilius',
'Petillius',
'Petronius',
'Pinarius',
'Piscius',
'Pisentius',
'Placidius',
'Plautius',
'Plinius',
'Plotius',
'Pollius',
'Pompeius',
'Pompilius',
'Pomponius',
'Pomptinus',
'Pontidius',
'Pontius',
'Popidius',
'Portius',
'Postumius',
'Potitius',
'Paesentius',
'Publicius',
'Pullo',
'Pupius',
'Quinctilius',
'Quinctius',
'Quirinius',
'Rabirius',
'Rufius',
'Rufrius',
'Rusonius',
'Rutilius',
'Sabucius',
'Sallustius',
'Salonius',
'Salvius',
'Scribonius',
'Secundinius',
'Secundius',
'Seius',
'Sempronius',
'Sennius',
'Sentius',
'Septimius',
'Sepunius',
'Sepurcius',
'Sergius',
'Sertorius',
'Servilius',
'Sestius',
'Sextilius',
'Sextius',
'Sidonius',
'Silius',
'Sittius',
'Socellius',
'Sornatius',
'Spurius',
'Statius',
'Statilius',
'Stertinius',
'Suedius',
'Sulpicius',
'Tadius',
'Talmudius',
'Tanicius',
'Tertinius',
'Tettidius',
'Tettienus',
'Tettius',
'Titiedius',
'Titius',
'Titinius',
'Trebatius',
'Trebellius',
'Treblanus',
'Tremellius',
'Tuccius',
'Tullius',
'Turullius',
'Ulpius',
'Umbrenius',
'Umbrius',
'Ummidius',
'Urgulanius',
'Uulius',
'Vagennius',
'Vagionius',
'Vagnius',
'Valerius',
'Varius',
'Vassenius',
'Vatinius',
'Vedius',
'Velius',
'Veranius',
'Verecundius',
'Vergilius',
'Verginius',
'Vesnius',
'Veturius',
'Vibenius',
'Vibidius',
'Vibius',
'Victricius',
'Viducius',
'Vinicius',
'Vipsanius',
'Vipstanus',
'Viridius',
'Virius',
'Visellius',
'Vitellius',
'Vitruvius',
'Vivianus',
'Volaginius',
'Volcatius',
'Volumnius',
'Volusenna',
'Volusenus',
'Volusius',
'Vorenus '
]

gen_data['roman_female_names'] = [
'Abelia',
'Acacallis',
'Acantha',
'Acca',
'Accalia',
'Achillea',
'Acquilina',
'Adalheidis',
'Adela',
'Adelia',
'Adelpha',
'Adelphia',
'Adolpha',
'Adorabella',
'Adorabelle',
'Adrastea',
'Adrastia',
'Adreana',
'Adriana',
'Adsiltia',
'Aegle',
'Aella',
'Aellae',
'Aello',
'Æmilia',
'Agacia',
'Agatha',
'Aggie',
'Aglaea',
'Aglea',
'Aigla',
'Alcestis',
'Alcippe',
'Alcmene',
'Alcyone',
'Alecto',
'Alena',
'Alexa',
'Alexandra',
'Alexandrea',
'Alexandria',
'Alexia',
'Alexina',
'Alexis',
'Alexus',
'Aloisia',
'Althaea',
'Althea',
'Amalthea',
'Amara',
'Amaranda',
'Amarantha',
'Ambrosia',
'Anastasia',
'Anatola',
'Andromeda',
'Angela',
'Angelia',
'Angelina',
'Angerona',
'Angeronia',
'Anna',
'Annthea',
'Anthea',
'Antonella',
'Antonetta',
'Antonia',
'Antonietta',
'Antonina',
'Aphrodisia',
'Apollonia',
'Aquilina',
'Arcadia',
'Arethusa',
'Ariadne',
'Arista',
'Artemisia',
'Astraea',
'Atalanta',
'Athanasia',
'Athena',
'Atropus',
'Augusta',
'Augustina',
'Aurelia',
'Aurora',
'Avelina',
'Bathildis',
'Batildis',
'Baucis',
'Bella',
'Bellatrix',
'Bellona',
'Benedicta',
'Berengari',
'Berengaria',
'Berenice',
'Bernice',
'Botilda',
'Brigid',
'Brigida',
'Brigitta',
'Britannia',
'Brittania',
'Cæcilia',
'Cælestis',
'Cælia',
'Calista',
'Calisto',
'Calligenia',
'Calliope',
'Callista',
'Calliste',
'Callisto',
'Calypso',
'Cambria',
'Camilla',
'Candace',
'Canute',
'Canutte',
'Cardea',
'Carina',
'Carme',
'Carmel',
'Carmella',
'Carmina',
'Carola',
'Carolina',
'Cassandra',
'Cassia',
'Cassiah',
'Cassiopea',
'Cassiopeia',
'Ceto',
'Chariclo',
'Charis',
'Chloe',
'Chloris',
'Christa',
'Christiana',
'Christina',
'Chrysanta',
'Chryseis',
'Chthonia',
'Circe',
'Clara',
'Claretta',
'Claricia',
'Clarissa',
'Claritia',
'Claudia',
'Clemency',
'Clementia',
'Clementina',
'Cleo',
'Cleopatra',
'Clio',
'Clotho',
'Clymene',
'Clytemnestra',
'Clytia',
'Clytie',
'Columbine',
'Concepta',
'Concordea',
'Concordia',
'Constantia',
'Constantina',
'Cora',
'Cordula',
'Core',
'Coretta',
'Corina',
'Corinna',
'Cornelia',
'Cosma',
'Crescentia',
'Cristina',
'Cybele',
'Cyma',
'Cynthia',
'Cyra',
'Cyriaca',
'Daria',
'Davena',
'Davina',
'Davinia',
'Dea',
'Decima',
'Delphina',
'Demetra',
'Demetria',
'Despoena',
'Diana',
'Dianna',
'Diantha',
'Diona',
'Dione',
'Discordia',
'Domina',
'Dominica',
'Domitilla',
'Dora',
'Dorcas',
'Dorothea',
'Dosia',
'Drusilla',
'Dulcea',
'Dulcia',
'Echo',
'Eione',
'Eleanora',
'Electra',
'Eliana',
'Elianna',
'Elwisia',
'Emilia',
'Estella',
'Eudocia',
'Eulia',
'Eunice',
'Euphemia',
'Euphrosyne',
'Europa',
'Eurydice',
'Eusebia',
'Eutropia',
'Evadne',
'Evangelina',
'Fabia',
'Fabiana',
'Fabianna',
'Fabiola',
'Fauna',
'Fausta',
'Faustina',
'Felicia',
'Feliciana',
'Felicitas',
'Flavia',
'Flora',
'Florentia',
'Floretta',
'Florine',
'Francisca',
'Frederica',
'Gæa',
'Galene',
'Gina',
'Gloria',
'Gloriana',
'Glorianna',
'Gobnata',
'Godleva',
'Gordiana',
'Gracilia',
'Grania',
'Granya',
'Gratia',
'Gusta',
'Halcyon',
'Halcyone',
'Hanna',
'Hebe',
'Hecate',
'Hecuba',
'Hekuba',
'Helena',
'Henrietta',
'Hera',
'Hercilia',
'Hermia',
'Hersilia',
'Herta',
'Hertha',
'Hester',
'Heva',
'Hilaria',
'Hippolyta',
'Honora',
'Honoria',
'Horatia',
'Hortensia',
'Hyacintha',
'Iantha',
'Ianthina',
'Idesta',
'Idetta',
'Idonea',
'Idothea',
'Igerna',
'Ilithyia',
'Immaculata',
'Io',
'Iola',
'Iona',
'Ione',
'Iphigenia',
'Irene',
'Isabela',
'Isabella',
'Isadora',
'Isaura',
'Isebella',
'Isidora',
'Ismene',
'Isolda',
'Itala',
'Iulia',
'Iuturna',
'Jacintha',
'Jacquelina',
'Jacquetta',
'Jana',
'Janae',
'Janina',
'Jessamine',
'Jillian',
'Joanna',
'Jocasta',
'Johanna',
'Josephina',
'Jucunda',
'Jules',
'Julia',
'Juliana',
'Junia',
'Juno',
'Justina',
'Juturna',
'Juventas',
'Kanutte',
'Karena',
'Karina',
'Katherina',
'Krista',
'Lachesis',
'Lælia',
'Lætitia',
'Larentia',
'Laura',
'Laurentia',
'Lauressa',
'Laurita',
'Laverna',
'Lavina',
'Lavinia',
'Leandra',
'Leanora',
'Lelia',
'Lene',
'Lenora',
'Lenore',
'Leona',
'Leontina',
'Leta',
'Leto',
'Leucothea',
'Lexus',
'Liana',
'Liboria',
'Ligea',
'Liliana',
'Linnaea',
'Livia',
'Liviana',
'Lora',
'Lorena',
'Lorina',
'Louisa',
'Lucasta',
'Lucetta',
'Lucia',
'Lucilla',
'Lucina',
'Lucretia',
'Lupa',
'Lutgardis',
'Lysistrata',
'Madelina',
'Madrona',
'Maea',
'Magdalena',
'Marcella',
'Marci',
'Marcia',
'Mare',
'Margarita',
'Maria',
'Mariana',
'Marica',
'Marina',
'Marisa',
'Marlena',
'Marquita',
'Martina',
'Mathilda',
'Mathildis',
'Matrona',
'Medea',
'Media',
'Medusa',
'Megaera',
'Melaena',
'Melete',
'Melita',
'Melitta',
'Melpomene',
'Mercia',
'Minerva',
'Mintha',
'Mirabella',
'Mneme',
'Mnemosyne',
'Modesta',
'Monica',
'Narcissa',
'Natalia',
'Nephele',
'Nereida',
'Nerida',
'Nerthus',
'Nicé',
'Nicholaa',
'Nidia',
'Nigella',
'Nox',
'Ocyrhoe',
'Odetta',
'Oenone',
'Ofelia',
'Ops',
'Orcades',
'Oriana',
'Osanna',
'Parthenope',
'Patricia',
'Paulina',
'Pax',
'Penelope',
'Pero',
'Petra',
'Petrina',
'Petronia',
'Petronilla',
'Phaedra',
'Philyra',
'Phoebe',
'Phoenix',
'Pia',
'Placida',
'Pleione',
'Polyhymnia',
'Polyxena',
'Pomona',
'Pompeia',
'Primitiva',
'Prisca',
'Priscilla',
'Procris',
'Proserpina',
'Proserpine',
'Prudentia',
'Psyche',
'Quintina',
'Quirina',
'Regina',
'Regula',
'Rena',
'Renae',
'Renata',
'Renita',
'Rhoda',
'Rica',
'Rina',
'Roberta',
'Rohesia',
'Rosa',
'Rosalia',
'Rosalina',
'Rosalind',
'Rosalinda',
'Rowena',
'Rowina',
'Roxana',
'Roxanna',
'Sabia',
'Sabina',
'Sabrina',
'Salvatrix',
'Samara',
'Saturnina',
'Scholastica',
'Scilla',
'Scylla',
'Seema',
'Selena',
'Septima',
'Sera',
'Seraphina',
'Serena',
'Severina',
'Sibilla',
'Sidony',
'Silva',
'Silvestra',
'Silvia',
'Sollemnia',
'Sperantia',
'Spes',
'Stephania',
'Sunniva',
'Susana',
'Susanna',
'Sylva',
'Sylvia',
'Tacita',
'Tanja',
'Tasia',
'Tatiana (Russian',
'Tatianna',
'Terpsichore',
'Terra',
'Thalia',
'Thecla',
'Theodora',
'Theodosia',
'Theophilia',
'Thyra',
'Timothea',
'Titania',
'Tryphena',
'Ulyssa',
'Undina',
'Undine',
'Urania',
'Ursa',
'Ursala',
'Ursina',
'Ursine',
'Ursula',
'Ursule',
'Urte',
'Valentina',
'Valeria',
'Valeriana',
'Varinia',
'Vena',
'Venus',
'Verbena',
'Verity',
'Veronica',
'Vesma',
'Vesna',
'Vesta',
'Viatrix',
'Victoria',
'Vincentia',
'Viola',
'Virginia',
'Vita',
'Vitalia',
'Viviana',
'Xanthe',
'Xanthia'
]

gen_data['roman_male_names'] = [
'Abelardus',
'Abrahamus',
'Acacius',
'Accius',
'Achaicus',
'Achill',
'Achilles',
'Achilleus',
'Acrisius',
'Actaeon',
'Acteon',
'Adalricus',
'Adelfonsus',
'Adelphus',
'Adeodatus',
'Adolfus',
'Adolphus',
'Adrastus',
'Adrianus',
'Ægidius',
'Ælia',
'Ælianus',
'Æmilianus',
'Æmilius',
'Aeneas',
'Æolus',
'Æschylus',
'Æson',
'Æsop',
'Æther',
'Ætius',
'Agapetus',
'Agapitus',
'Agapius',
'Agathangelus',
'Agrippa',
'Ahasuerus',
'Aigidius',
'Aiolus',
'Ajax',
'Alair',
'Alaricus',
'Albanus',
'Alberic',
'Albericus',
'Albertus',
'Albinus',
'Albus',
'Alcaeus',
'Alcander',
'Alcimus',
'Alcinder',
'Alerio',
'Alexandrus',
'Alexis',
'Alexius',
'Alexus',
'Alfonsus',
'Alfredus',
'Almericus',
'Aloisius',
'Aloysius',
'Alphaeus',
'Alpheaus',
'Alpheus',
'Alphoeus',
'Alphonsus',
'Alphonzus',
'Alvinius',
'Alvredus',
'Amadeus',
'Amaliricus',
'Amandus',
'Amantius',
'Amarandus',
'Amaranthus',
'Amatus',
'Ambrosianus',
'Ambrosius',
'Amedeus',
'Americus',
'Amlethus',
'Amletus',
'Amor',
'Ampelius',
'Amphion',
'Anacletus',
'Anastasius',
'Anastatius',
'Anastius',
'Anatolius',
'Androcles',
'Andronicus',
'Anencletus',
'Angelicus',
'Angelus',
'Anicetus',
'Antigonus',
'Antipater',
'Antoninus',
'Antonius',
'Aphrodisius',
'Apollinaris',
'Apollo',
'Apollonius',
'Appius',
'Aquila',
'Arcadius',
'Archelaus',
'Archippus',
'Argus',
'Aries',
'Aristaeus',
'Aristarchus',
'Aristides',
'Aristobulus',
'Aristocles',
'Aristodemus',
'Aristotle',
'Arminius',
'Arnoldus',
'Arsenius',
'Artemidorus',
'Artemisius',
'Artorius',
'Asclepius',
'Athamus',
'Athanasius',
'Atilius',
'Atticus',
'Attilius',
'Attius',
'August',
'Augustinus',
'Augustus',
'Aulus',
'Aurelianus',
'Aurelius',
'Auriel',
'Avitus',
'Bacchus',
'Balius',
'Bartholomaeus',
'Bartolomaeus',
'Basilius',
'Benedictus',
'Benignus',
'Berengarius',
'Beringarius',
'Bernardus',
'Bertramus',
'Blasius',
'Boniface',
'Bonifatius',
'Brendanus',
'Brennius',
'Brianus',
'Bricius',
'Brictius',
'Brutus',
'Cadmus',
'Cæcilius',
'Cæcus',
'Cælestinus',
'Cælestis',
'Cælinus',
'Cælius',
'Cæsar',
'Caiaphas',
'Caietanus',
'Caius',
'Caligula',
'Calix',
'Callias',
'Callicrates',
'Callistrate',
'Callistratus',
'Callistus',
'Callixtus',
'Calogerus',
'Calvinus',
'Cambyses',
'Camillus',
'Canicus',
'Canutus',
'Capaneus',
'Caratacus',
'Carmine',
'Carol',
'Carolus',
'Carpus',
'Casimiria',
'Cassian',
'Cassiel',
'Cassius',
'Castor',
'Catigernus',
'Cato',
'Catotigernos',
'Catutigernos',
'Celer',
'Celsus',
'Cephalus',
'Cephas',
'Cepheus',
'Cerberus',
'Ceyx',
'Charon',
'Chiron',
'Chlotharius',
'Christianus',
'Christophorus',
'Chrysanthus',
'Chrysaor',
'Chryses',
'Cicero',
'Cimon',
'Clarus',
'Claudius',
'Cledaucus',
'Cleisthenes',
'Clemens',
'Clement',
'Clementinus',
'Clementius',
'Cleopas',
'Cleopatros',
'Cleophas',
'Cletes',
'Cletis',
'Cletus',
'Climacus',
'Clitus',
'Clopas',
'Clophas',
'Clotenus',
'Columba',
'Columban',
'Columbanus',
'Columbus',
'Constans',
'Constant',
'Constantine',
'Constantinus',
'Constantius',
'Consus',
'Cornelius',
'Cornell',
'Cosmo',
'Creon',
'Crescentius',
'Crispinus',
'Crispus',
'Crius',
'Cronus',
'Cupid',
'Cupido',
'Cyprian',
'Cyprianus',
'Cyriacus',
'Cyrillus',
'Cyrus',
'Daedalos',
'Daedalus',
'Damianus',
'Damocles',
'Darius',
'Decebalus',
'Decimus',
'Delicius',
'Delphinius',
'Demetrius',
'Democritus',
'Deodatus',
'Desiderius',
'Deus',
'Deusdedit',
'Didacus',
'Didagus',
'Didymus',
'Diodorus',
'Diodotus',
'Diomed',
'Diomedes',
'Dionysius',
'Dionysus',
'Dioscuri',
'Dominicus',
'Domitian',
'Domitianus',
'Domitius',
'Donatus',
'Dorianus',
'Dorotheus',
'Dorus',
'Draco',
'Drustanus',
'Drusus',
'Duilius',
'Eduardus',
'Efrem',
'Egidius',
'Egnatius',
'Eleutherius',
'Elianus',
'Eligius',
'Elpidius',
'Emericus',
'Emidius',
'Emmanuel',
'Emygdius',
'Ennius',
'Eolus',
'Epaphroditus',
'Ephesius',
'Ephrem',
'Epictetus',
'Erasmus',
'Erastus',
'Erebus',
'Ernestus',
'Ether',
'Euclid',
'Eugenius',
'Eulalius',
'Euphemius',
'Eusebius',
'Eustachius',
'Eustorgius',
'Euthymius',
'Eutropius',
'Eutychius',
'Evander',
'Evangelus',
'Evaristus',
'Fabianus',
'Fabius',
'Fabricius',
'Faunus',
'Faust',
'Faustinus',
'Faustulus',
'Faustus',
'Felicianus',
'Felix',
'Ferox',
'Festus',
'Fidelis',
'Fido',
'Filbertus',
'Firminus',
'Flavian',
'Flavius',
'Florentius',
'Florian',
'Florianus',
'Fortunatus',
'Franciscus',
'Fredericus',
'Frigidian',
'Frithunantus',
'Fulgentius',
'Fulvius',
'Gabinus',
'Gabrielus',
'Gaheris',
'Gaius',
'Galenus',
'Gallus',
'Gavius',
'Gemini',
'Gennadius',
'Gentius',
'Georgius',
'Geraldus',
'Germanus',
'Gerontius',
'Gervasius',
'Gieronymus',
'Gilebertus',
'Gilibertus',
'Gillebertus',
'Glaucia',
'Gordian',
'Gordianus',
'Gracilis',
'Gratian',
'Gratianus',
'Gregorius',
'Griffinus',
'Gruffinus',
'Guillelmus',
'Gundisalvus',
'Gurganus',
'Gurgintius',
'Gustavus',
'Hades',
'Hadrian',
'Hadrianus',
'Hampus',
'Hasdrubal',
'Hector',
'Heironymus',
'Helier',
'Heliodorus',
'Helladius',
'Hemigidius',
'Henricus',
'Hephaestus',
'Heracleitus',
'Heraclitus',
'Herbertus',
'Hercules',
'Hermanus',
'Hermes',
'Herminius',
'Hermocrates',
'Hermolaus',
'Herod',
'Herodotus',
'Hieronymus',
'Hilarius',
'Hippocrates',
'Hippolytus',
'Homerus',
'Honoratus',
'Honorius',
'Honorus',
'Horatius',
'Hortensius',
'Horus',
'Hrabanus',
'Hubertus',
'Hugo',
'Humbertus',
'Humfridus',
'Hunfridus',
'Hyacinthus',
'Hyginus',
'Hyman',
'Hymen',
'Hymenaeus',
'Hypatius',
'Hypatus',
'Iacchus',
'Iacobus',
'Iacomus',
'Ianuarius',
'Ianus',
'Icarus',
'Iduma',
'Ignatius',
'Innocentius',
'Iohannes',
'Iovannis',
'Iovis',
'Ireneus',
'Isaias',
'Isidorus',
'Isocrates',
'Italus',
'Iulius',
'Jacinthus',
'Jacobus',
'Jacomus',
'Januarius',
'Janus',
'Jason',
'Jeremias',
'Jericho',
'Jesus',
'Joannes',
'Jodocus',
'Johan',
'Johannes',
'Jonas',
'Josephus',
'Josias',
'Jove',
'Jovilios',
'Jovilius',
'Judas',
'Julian',
'Julianus',
'Julius',
'Junius',
'Junonius',
'Jupiter',
'Justinus',
'Justus',
'Juvenal',
'Juvenalis',
'Kaius',
'Kanut',
'Kanutus',
'Ladislaus',
'Lælianus',
'Lælius',
'Latinus',
'Laurens',
'Laurentinus',
'Laurentius',
'Laurus',
'Lazarus',
'Leander',
'Lebbaeus',
'Lebuin',
'Lebuinus',
'Leo',
'Leonides',
'Leonius',
'Leontinus',
'Leontius',
'Lexus',
'Liber',
'Liberius',
'Linus',
'Livianus',
'Livius',
'Longinus',
'Lotharius',
'Lucan',
'Lucanus',
'Lucas',
'Lucianus',
'Lucifer',
'Luciferus',
'Lucius',
'Lucretius',
'Ludo',
'Ludovic',
'Ludovicus',
'Lugovalio',
'Lupus',
'Lycaon',
'Lycurgus',
'Lysander',
'Lysimachus',
'Macarius',
'Macedon',
'Magnus',
'Manfredus',
'Manilius',
'Manius',
'Manlius',
'Marc',
'Marcellinus',
'Marcellus',
'Marcius',
'Marcus',
'Marian',
'Marianus',
'Marinus',
'Marion',
'Maris',
'Marius',
'Mars',
'Martialis',
'Martinus',
'Martis',
'Martius',
'Maurice',
'Mauricius',
'Maurus',
'Maxentius',
'Maxim',
'Maximian',
'Maximilian',
'Maximilianus',
'Maximillian',
'Maximinus',
'Maximus',
'Meleager',
'Mencius',
'Menelaus',
'Mercurius',
'Mercury',
'Merianus',
'Merinus',
'Merlinus',
'Methodius',
'Milo',
'Milon',
'Modestus',
'Naevius',
'Narcissus',
'Nazarius',
'Nedebaeus',
'Neleus',
'Nemo',
'Neoptolemus',
'Neptune',
'Neptunus',
'Nereus',
'Nero',
'Nerva',
'Nicator',
'Nicephorus',
'Nicodemus',
'Nicolaus',
'Nicomedes',
'Nicon',
'Nicostratus',
'Nigellus',
'Oceanus',
'Octavian',
'Octavianus',
'Octavius',
'Odoacer',
'Oedipus',
'Oeneus',
'Olympus',
'Onesimus',
'Onesiphorus',
'Orlandus',
'Osvaldus',
'Ovid',
'Ovidius',
'Pæon',
'Palaemon',
'Palinurus',
'Pamphilus',
'Pancratius',
'Pantaleon',
'Pantera',
'Paracelsus',
'Paramonus',
'Paschalis',
'Patricius',
'Patroclus',
'Paulinus',
'Paulus',
'Pegasus',
'Pelagius',
'Peregrinus',
'Pericles',
'Petronius',
'Petrus',
'Phaedrus',
'Phanes',
'Philandrus',
'Philetus',
'Philippus',
'Philocrates',
'Philomelus',
'Philomenus',
'Philotheus',
'Phocas',
'Phoebus',
'Phoenix',
'Pholus',
'Phorcys',
'Photius',
'Phrixus',
'Pilate',
'Pius',
'Placidus',
'Plato',
'Plinius',
'Pliny',
'Plutarch',
'Plutarchus',
'Pluto',
'Pollux',
'Polycarp',
'Polycarpus',
'Polydeuces',
'Polydorus',
'Pompeius',
'Pompilius',
'Pontius',
'Pontus',
'Porcius',
'Porphyrius',
'Porphyry',
'Portumnus',
'Portunus',
'Poseidon',
'Poseidon',
'Posidonius',
'Premislaus',
'Primitivus',
'Primus',
'Priscus',
'Prochorus',
'Procopius',
'Prometheus',
'Prosperus',
'Proteus',
'Prudentius',
'Ptolemaeus',
'Publius',
'Pyrrhus',
'Pythius',
'Quintinus',
'Quintus',
'Quique',
'Quirinus',
'Rabanus',
'Raguel',
'Ramirus',
'Rannulfus',
'Rasmus',
'Rastus',
'Reginaldus',
'Regulus',
'Remigius',
'Remus',
'Renatus',
'Reynaldus',
'Ricardus',
'Riothamus',
'Robertus',
'Rodbertus',
'Rogatus',
'Rogelius',
'Rogellus',
'Rogerius',
'Rollo',
'Romanus',
'Romulus',
'Rudolphus',
'Rufinus',
'Rufus',
'Sabinus',
'Salomon',
'Salvator',
'Sanctius',
'Sandalius',
'Saturn',
'Saturninus',
'Saturnus',
'Saul',
'Scævola',
'Sebastianus',
'Secundinus',
'Secundus',
'Seleucus',
'Seneca',
'Septimus',
'Seraphinus',
'Sergius',
'Servius',
'Severianus',
'Severinus',
'Severus',
'Sextilius',
'Sextus',
'Sidonius',
'Silenus',
'Silvanus',
'Silvester',
'Silvius',
'Sisera',
'Socrates',
'Sophocles',
'Sophronius',
'Sophus',
'Sostratus',
'Spartacus',
'Spurius',
'Stamatius',
'Stanislas',
'Stanislaus',
'Stasius',
'Stefanus',
'Stephanus',
'Stylianus',
'Summanus',
'Tacitus',
'Tatianus',
'Tatius',
'Telesphorus',
'Terentius',
'Terminus',
'Tertius',
'Thaddaeus',
'Thelonius',
'Themistocles',
'Theobaldus',
'Theocles',
'Theocritus',
'Theodorus',
'Theodosius',
'Theodotus',
'Theodulus',
'Theophilus',
'Theophylact',
'Theophylactus',
'Theudoricus',
'Thiudoricus',
'Thorbernus',
'Thracius',
'Thucydides',
'Tiberius',
'Tiburtius',
'Timæus',
'Timeus',
'Timoteus',
'Timotheus',
'Titanius',
'Titanus',
'Titus',
'Tobijah',
'Torbernus',
'Torquatus',
'Tycho',
'Ulixes',
'Ulricus',
'Ulysses',
'Uranus',
'Urbane',
'Urbanus',
'Urbgenius',
'Urianus',
'Urias',
'Ursinus',
'Ursus',
'Valentinus',
'Valerian',
'Valerianus',
'Valerius',
'Varinius',
'Varius',
'Velius',
'Venceslaus',
'Vergilius',
'Verissimus',
'Verus',
'Vesper',
'Vesperus',
'Viator',
'Victor',
'Victorinus',
'Victorius',
'Viggo',
'Vincentius',
'Vinicius',
'Virgilius',
'Virginius',
'Vitalis',
'Vitus',
'Vivianus',
'Vortigernus',
'Vulcan',
'Wenceslas',
'Wenceslaus',
'Wido',
'Wilhelmus',
'Xanthus',
'Zacchaeus',
'Zeno',
'Zephyrinus',
'Zephyrus',
'Zoroaster',
'Zoroastres',
'Zosimus',
'Zoticus'
];
