gen_data["Celtic_male_common"] = [
'Agedillios', 'Ateponius', 'Banui', 'Cottius', 'Criciro', 'Andosteni', 'Samais', 'Talius', 'Toutio', 'Vercombogius'
]
gen_data["Celtic_male_uncommon"] = [
'Adebugi', 'Adiatorix', 'Adnamati', 'Advorix', 'Agedillios', 'Agisilius', 'Albic', 'Allobroxus', 'Alpius', 'Ambaxius', 'Ambillus', 'Ambiorix', 'Andecamulos', 'Andecarius', 'Andegasi', 'Andergi', 'Andosteni', 'Annmoris', 'Artos', 'Ateano', 'Atepagus', 'Ateponius', 'Atesios', 'Atessatis,Atporix', 'Atrectus', 'Atrixtos', 'Aventinus', 'Balorix', 'Banui', 'Bellognatus', 'Bilicedo', 'Bimmos', 'Bodocenos', 'Borili', 'Borso', 'Borvonicus', 'Bratronos', 'Britomartus', 'Brocchus', 'Bussumarus', 'Cabiros', 'Cacurio', 'Cambus', 'Camerianus', 'Camulixus', 'Caractacus', 'Caracus', 'Caramantius', 'Carathounus', 'Carigo', 'Carix', 'Carugenus', 'Cassicius', 'Cassivellaunus', 'Catacus', 'Cathirix', 'Caticorix', 'Cattabus', 'Cattuvir', 'Catuenus', 'Catumandus', 'Catusius', 'Catuvolcus', 'Cauarius', 'Celtillus', 'Cenno', 'Cimarus', 'Cingetorix', 'Cinto', 'Coaeddus', 'Cobledulitavus', 'Cobnertius', 'Cocolitanus', 'Cogidubnus', 'Comnertus', 'Congonetiacus', 'Contesilo', 'Contoutos', 'Corbagni', 'Corio', 'Cornutos', 'Cotillus', 'Cottius', 'Cottro', 'Covertomotul', 'Covirius', 'Criciro', 'Cunigni', 'Cunobelinos', 'Curcagnus', 'Dagillus', 'Dagobius', 'Dalagni', 'Dattovir', 'Deoratus', 'Dercillus', 'Devus', 'Diorix', 'Divicatus', 'Dobagni', 'Doiros', 'Doninus', 'Donnadu', 'Donnus', 'Drutalus', 'Dumnorix', 'Dumnovellaunus', 'Ebicatos', 'Eburio', 'Elusconos', 'Endovellicus', 'Epatus', 'Epetinus', 'Eporedorix', 'Epos', 'Epotsorouidus', 'Ercaviccas', 'Escincos', 'Excingillus', 'Exsomnus', 'Frontú', 'Gabrus', 'Genetlus', 'Grimiggni', 'Iantinus', 'Iccauos', 'Iccinus', 'Ientius', 'Licnos', 'Litavis', 'Litugenius', 'Lugotorix', 'Lugurix', 'Macareus', 'Maccis', 'Magurius', 'Mando', 'Martalos', 'Martoualos', 'Meddugnatus', 'Megaravico', 'Melmandus', 'Messillus', 'Metilius', 'Moddagni', 'Morirex', 'Netacari', 'Nisigni', 'Oclicnos', 'Ollognus', 'Oppianicnos', 'Orgetorix', 'Perrius', 'Praesutagus', 'Reginius', 'Remicus', 'Rextugenos', 'Rittuvvecas', 'Sacrovir', 'Sagillus', 'Samais', 'Samocenus', 'Segovax', 'Senecio', 'Senocarus', 'Senovir', 'Sollovico', 'Talius', 'Tallutius', 'Tanco', 'Tarbunus', 'Tasciovanus', 'Tascius', 'Tasgetios', 'Tauri', 'Togodumnus', 'Toutio', 'Toutobocio', 'Toutos', 'Trenacatus', 'Tritos', 'Tuticanius', 'Ulccagni', 'Vallius', 'Vallo', 'Vebru', 'Vectimarus', 'Vectitos', 'Velagenus', 'Velitas', 'Velorius', 'Velugni', 'Vendogni', 'Venextos', 'Venicarus', 'Venixamus', 'Vennonius', 'Vepotalus', 'Vercatus', 'Vercassivellaunus', 'Vercingetorix', 'Vercombogius', 'Versignos', 'Verter', 'Vertros', 'Veruico', 'Vicixtillus', 'Victi', 'Vindedo', 'Viranus', 'Viratus', 'Viriacius', 'Virico', 'Virisimi', 'Virocantus', 'Vitousurix', 'Vlatcani', 'Vlatos', 'Vlatugni', 'Vocorix', 'Vopiscus', 'Vosegus', 'Voteporix'
]
gen_data["Celtic_female_common"] = [
'Adnamu', 'Aduorix', 'Anderica', 'Cotu', 'Loucita', 'Mata', 'Nama', 'Sumela', 'Tancorix', 'Viccu'
]
gen_data["Celtic_female_uncommon"] = [
'Abrexta', 'Adginna', 'Adiania', 'Adiega', 'Admata', 'Adnamitu', 'Adnamu', 'Aduorix', 'Advorix', 'Aesica', 'Agedia', 'Aia', 'Albina', 'Alla', 'Alleticia', 'Allusa', 'Alpina', 'Alteurita', 'Andebrocirix', 'Anderca', 'Anderica', 'Anderina', 'Andoca', 'Annama', 'Arrotala', 'Atectorigiana', 'Atessatia', 'Atioxta', 'Auctiona', 'Audata', 'Aulricmara', 'Banna', 'Banona', 'Barita', 'Betudaca', 'Bileseton', 'Billia', 'Borissa', 'Boudenna', 'Boudicca', 'Boudilatis', 'Brocchia', 'Buscilla', 'Cabrilla', 'Cabura', 'Caburena', 'Caccosa', 'Camula', 'Cantexta', 'Carantia', 'Carantusa', 'Carata', 'Caretosa', 'Carissa', 'Cartimandua', 'Castina', 'Catalia', 'Catica', 'Catronia', 'Catta', 'Cattulla', 'Caturica', 'Caura', 'Cenna', 'Cenos', 'Centogenea', 'Centusmia', 'Cigemma', 'Cinia', 'Coblanuo', 'Cobnerta', 'Cobronia', 'Comatimara', 'Condexua', 'Congenetia', 'Corasia', 'Corobilla', 'Cottina', 'Cotu', 'Cotuconi', 'Cricconia', 'Cunacena', 'Cunoarda', 'Cunovinda', 'Dania', 'Dannumara', 'Danu', 'Deuilla', 'Diligenta', 'Diveca', 'Donilla', 'Dubna', 'Eliomara', 'Elovissa', 'Epilla', 'Eppaxta', 'Eppia', 'Eskenga', 'Exapia', 'Excinga', 'Excingilla', 'Exobna', 'Fimmilene', 'Friagabi', 'Genna', 'Genucia', 'Gnatia', 'Huctia', 'Iantulla', 'Iatta', 'Iccia', 'Ilateuta', 'Inderca', 'Isosae', 'Lanipendia', 'Leuca', 'Leucona', 'Lituccia', 'Litugena', 'Loucita', 'Loucitta', 'Maccira', 'Magusatia', 'Manduissa', 'Martilia', 'Martna', 'Mata', 'Mataura', 'Matina', 'Matonia', 'Mattosa', 'Matugena', 'Medlotama', 'Melicia', 'Messilia', 'Metilia', 'Moriena', 'Mottu', 'Nama', 'Namia', 'Namiola', 'Namu', 'Namuta', 'Nantia', 'Nantiorix', 'Nerta', 'Netelia', 'Nitiogenna', 'Ollia', 'Orbiana', 'Origena', 'Oxidubna', 'Paulla', 'Pera', 'Peula', 'Potita', 'Reginia', 'Rematia', 'Ressatu', 'Ressona', 'Reticiana', 'Ritomara', 'Sagila', 'Sama', 'Samaxa', 'Samia', 'Sammiola', 'Sattomata', 'Sedecennis', 'Segolia', 'Sennaucia', 'Severa', 'Sila', 'Suaduilla', 'Sucaria', 'Sueta', 'Sumela', 'Talavica', 'Talisia', 'Taluppa', 'Talussa', 'Tancorix', 'Tascilla', 'Taurica', 'Teolugnia', 'Teuta', 'Tritia', 'Trocina', 'Valagenta', 'Valicina', 'Vebrumna', 'Veca', 'Vectinia', 'Vellibia', 'Veniala', 'Venicia', 'Venisama', 'Venitouta', 'Venixama', 'Venna', 'Vennonia', 'Verctissa', 'Verica', 'Verodumna', 'Vicana', 'Viccu', 'Viccus', 'Victisirana', 'Vindauscia', 'Viralira', 'Viratia', 'Virciu', 'Viriondaga', 'Visurix', 'Vlatucia', 'Vocara', 'Vrittia', 'Vrogenia'
]

gen_data["Celtic_male_name"] = {
    '1-80': '{Celtic_male_first_common}',
    '81-100': '{Celtic_male_first_uncommon}'
}
gen_data["Celtic_female_name"] = {
    '1-80': '{Celtic_female_first_common}',
    '81-100': '{Celtic_female_first_uncommon}'
}


