gen_data['statue'] = [
  'a {statue_material} statue of a {statue_type}.  {statue_condition_unusal}'
]
gen_data['statue_type'] = {
	'1': '{statue_simple_person}',
	'2': '{statue_simple_animal}',
	'3': '{statue_simple_monster}',
	'4': '{statue_simple_inanimate}',
	'5': '{statue_complex_event}',
	'6': '{statue_complex_combo}'
}
gen_data['statue_simple_person'] = {
	'01-05': '(deity)',
	'06-10': '(saint)',
	'10-15': '(religious leader)',
	'16-20': '(scholar)',
	'21-25': '(wizard)',
	'26-30': '(knight)',
	'31-35': '(king, royalty, noble, or other authority figure)',
	'36-40': '(barbaric warrior)',
	'41-45': '(heroic warrior)',
	'46-50': '(child or baby)',
	'51-55': '(“victim”)',
	'56-60': '(“vanquished”)',
	'61-65': '(seems to be a beggar)',
	'66-70': '(nondescript or faceless)',
	'71-75': '(craftsman)',
	'76-80': '(nondescript commoner)',
	'81-85': '(performer of music or other)',
	'86-90': '(artist, poet, etc.)',
	'91-95': '(builder or engineer)',
	'96-00': '(owner of premises)'
}
gen_data['statue_simple_animal'] = {
	'01-05': 'Ape',
	'06-10': 'Bear',
	'10-15': 'Bird',
	'16-20': 'Boar',
	'21-25': 'Cat',
	'26-30': '{bird_of_prey}',
	'31-35': 'Dog',
	'36-40': 'Dog',
	'41-45': 'Duck',
	'46-50': 'Elephant',
	'51-55': '{aquitic_creatures}',
	'56-60': '{bird_of_prey}',
	'61-65': 'Horse',
	'66-70': 'Horse',
	'71-75': 'Lion or tiger',
	'76-80': '{aquitic_creatures}',
	'81-85': 'Bull',
	'86-90': 'Rooster',
	'91-95': 'Snake',
	'96-00': 'Wolf '
}
gen_data['statue_simple_monster'] = {
	'01-05': 'giant bat',
	'06-10': 'centaur',
	'10-15': '{fantastic_animal}',
	'16-20': 'dragon',
	'21-25': 'genie',
	'26-30': '{fantastic_animal}',
	'31-35': '{fey_creature}',
	'36-40': 'gargoyle',
	'41-45': 'giant',
	'46-50': 'giant insect',
	'51-55': 'giant beetle',
	'56-60': 'manticore',
	'61-65': 'minotaur',
	'66-70': 'serpent',
	'71-75': '{goblinoild_race}',
	'76-80': '{goblinoild_race}',
	'81-85': 'cockatrice',
	'86-90': 'sphinx',
	'91-95': '{fantastic_animal}',
	'96-00': 'unicorn '
}
gen_data['statue_simple_inanimate'] = {
	'01-05': 'Abstract blob form',
	'06-10': 'Abstract jumbled form',
	'10-15': 'Abstract spheres',
	'16-20': 'Balancing scales, wings, or other symbolic representation of a concept or ideal',
	'21-25': 'Cubes',
	'26-30': 'Diorama of an outdoor location',
	'31-35': 'A mobile of hanging hoops',
	'36-40': '{musical_instruments}',
	'41-45': 'Spiral',
	'46-50': 'Household item (butter churn, cookpot, etc).',
	'51-55': 'Model of a house or castle',
	'56-60': 'Model of a room',
	'61-65': 'Mushroom or fungus',
	'66-70': 'Representation (possibly prototype) of a machine or mechanism',
	'71-75': 'Sculpted pillar',
	'76-80': 'Skull or skeletal',
	'81-85': 'Sphere or cone',
	'86-90': 'Symbol on pedestal',
	'91-95': 'Tree',
	'96-00': 'Weapon'
}
gen_data['statue_complex_event'] = {
	'01-05': 'A funeral',
	'06-10': 'A meal',
	'11-15': 'A significant discovery',
	'16-20': 'A significant purchase',
	'21-25': 'Adulthood rites',
	'26-30': 'An assassination',
	'31-35': 'An important argument or dispute',
	'36-40': 'Battle scene (“bridge”)',
	'41-45': 'Battle scene (“victory”)',
	'46-50': 'Conferring knighthood or status',
	'51-55': 'Conferring ownership',
	'56-60': 'Execution',
	'61-65': 'Exiling of a rebel or criminal',
	'66-70': 'Greeting important guest',
	'71-75': 'Marriage',
	'76-80': 'One-on-one combat',
	'81-85': 'Religious scene (“blessings”)',
	'86-90': 'Religious scene (“judgment”)',
	'91-95': 'Scene from the specific history or backstory',
	'96-00': 'Signing of a treaty or accord'
}
gen_data['statue_complex_combo'] = {
	'01-05': '{statue_simple_animal} and {statue_simple_inanimate}',
	'06-10': '{statue_simple_animal} and {statue_simple_monster}',
	'11-15': 'Family of {statue_simple_animal}s',
	'16-20': '{statue_simple_person} and their family',
	'21-25': 'Group of {statue_simple_animal}',
	'26-30': '{statue_simple_monster} and {statue_simple_inanimate}',
	'31-35': '{statue_simple_person} and {statue_simple_animal}',
	'36-40': '{statue_simple_person} and {statue_simple_inanimate}',
	'41-45': '{statue_simple_person} and {statue_simple_monster}',
	'46-50': '{statue_simple_person} and {statue_simple_person}',
	'51-55': 'Terra-cotta {2d6} statues of a {statue_simple_person} lined up in procession',
	'56-60': 'Terra-cotta {2d6} statues of a {statue_simple_animal} lined up in procession',
	'61-65': '{statue_simple_person}, {statue_simple_person}, and {statue_simple_person}',
	'66-70': 'Totem-pole arrangement of {1d3+2} {statue_simple_animal}s',
	'71-75': 'Totem-pole arrangement of {1d3+2} mix of Monsters and Animals',
	'76-80': 'Totem-pole arrangement of {1d3+2} {statue_simple_monster}s',
	'81-85': '{statue_simple_animal} and {statue_simple_animal}',
	'86-90': '{statue_simple_inanimate} and {statue_simple_inanimate}',
	'91-95': '{statue_simple_monster} and {statue_simple_monster}',
	'96-00': 'Two {statue_simple_monster}s'
}
gen_data['statue_condition_unusal'] = {
	'01-04': 'Parts of the statue are broken off and are now lost.',
	'05-08': 'The status seems to have had small parts of it chipped.',
	'09-12': 'Someone seems to have hacked away at the statue with blades of some sort.',
	'13-16': 'There are parts of the statue which have been partially melted.',
	'17-20': 'Scorch marks cover the statue in several locations',
	'21-24': 'Parts of the statue seem to have been partially disintegrated',
	'25-28': 'The statue has been painted over several times by different parties with different agendas',
	'29-32': 'The statue has been reverently draped with cloth',
	'33-36': 'The statue looks to be in perfect condition',
	'37-40': 'The statue is a resting place for a flock of birds, and is now covered in guano',
	'41-44': 'The statue has been eroded by the elements',
	'45-48': 'There are noticable cracks in the statue',
	'49-52': 'Parts of the statue are broken off and now lay at the base of the statue',
	'53-56': 'Graffiti, written in several languages, covers part of it',
	'57-60': 'The statue has been toppled over',
	'61-64': 'There are strange pockmarks and holes in the statue',
	'65-68': 'The statue is unnaturally coverend in condensation and frost',
	'69-72': 'The statue is unnaturally hot to the touch',
	'73-76': 'The statue is half buried in the ground',
	'77-80': 'The statue has been warped by some unknown power',
	'81-84': 'The statue glows in the dark with some sort of phosphorescent',
	'85-88': 'The statue is covered in moss',
	'89-92': 'The statue is covered in cobwebs',
	'93-96': 'The statue has been smashed apart, but it is still recognizeable.',
	'97-00': 'The statue has been cut.'
}
gen_data['statue_material'] = {
	'01-04': 'brass',
	'05-08': 'bronze',
	'09-12': 'clay',
	'13-16': 'clay',
	'17-20': 'copper',
	'21-24': 'copper',
	'25-28': 'granite',
	'29-32': 'granite',
	'33-36': 'iron',
	'37-40': 'jade',
	'41-44': 'marble',
	'45-48': 'obsidian',
	'49-52': 'quartz',
	'53-56': 'stone',
	'57-60': 'stone',
	'61-64': 'stone'
}
