gen_data['minor_magic_item'] = [
	'Wooden Spoon.  Carved with rune for "food".  When tapped on an inert organic or semi-organic material (wood, dirt) it turns that stuff into edible foodstuffs, although it will be mushy and unpalatable.',
	'Amulet of Hope.  Shines as bright as a candle, but only when there are no other light sources.  Light points back towards dungeon entrance, vaguely.  Hums reassuringly when clutched, and warms your hand.',
	'Orphan\'s Top.  Cannot be spun if there are any invisible undead nearby.  ',
	'Ring of the Adventurous Limb.  If worn on a hand, the entire arm will vanish.  It will return after 24 hours have elapsed.  Roll a d10: 1 - tattoo on arm, 2 - arm injured, 3 - gained a ring, probably a wedding ring, 4 - ring missing, 5-10 - nothing special.  It will have a similar effect on legs.',
	'Dust of De-Appearance.  Can make things invisible, but wears off if the object moves, is moved, or even wiggles a bit.  Best used on inanimate objects or people who can hold really, really, still.',
	'Paired Scrolls.  Whatever is written on one appears on the other.  Give players a 3"x5" card to write on, to limit how much they can write.',
	'Statuette of Baal.  Can be "fed" gold to grow larger, adding to its.  Starts out the size of a gold coin.  Becomes more complex as it grows larger, adds features and companions.  If grown to the size of 100,000 gp, golden tablet reveals great secret.  (Does not create or destroy gold, just absorbs it.)  If grown to 1,000,000 gp, it will come alive and try to take over the world.',
	'Book of Epic Boredom.  When reading, save vs sleep.',
	'Black Cigarette.  When smoked, it creates a huge cloud of smoke and allows the smoker to see through smoke and fog.  Can be smoked for 5 minutes (or 5 one-minute segments).',
	'Colorthief\'s Brush.  This paintbrush has a needle on the back.  If you prick something, you steal all the color from it, but can later paint with those same brilliant colors (stored in the brush, controlled by imagination).  If a book is pricked, it will steal the words.  The book can then be reconstructed, but it takes a few days of writing for it to be recovered.',
	'Sleeping Draught.  Sleep TWICE AS HARD for four hours.  You get a full night\'s rest, but cannot be woken up.  Unwilling targets get a save.',
	'Love Potion.',
	'Exploserous Carnelian.  When activated, begins to glow hotter and hotter.  Explodes like a stick of dynamite after 1d2+2 rounds.',
	'Mighty Acorn.  When thrown on the ground, immediately grows into a 20\' oak.',
	'Mechanical Torchbearer.  Follows the associated amulet, or whoever is wearing it.  Can hold 6 torches, and relight a new one as the old one burns out.  Looks like a mechanical spider, 5\' in diameter.',
	'Penguin tokens (1d6).  Summons an 80 lb emperor penguin.  On land, cannot do anything except waddle to where you direct.  In water, can attack as a 1 HD creature.  Is destroyed/killed if it takes any damage.  Reverts to a small (1") wooden token after 1 minute.',
	'Saint\'s Bones.  About the size of a cigar box.  Contains mandible + some carpals.  Will rattle ominously when a lie is uttered nearby.',
	'Amber Comb.  Any lightning attack within 10\' is diverted to the comb instead.  If the comb takes 6 or more damage (it is not immune to lightning), it shatters.',
	'Chewed Bone.  When chewed, it fills the air with the smell of delicious fresh meat.  This is strong enough to mask other odors.',
	'Bottle of Light.  When swung overhead (a small chain is attached for this purpose) the bottle absorbs ambient light.  Later, the bottle can be unstoppered to allow the light back out again.  Can hold up to 5 rounds of light.  Special properties of light are preserved: moonlight can induce lycanthropy, for example.',
	'Silver silk handkerchief.  3\' on a side.  On the command word, it becomes as hard as thick steel.  A second command word reverts.',
	'Silver silk rope.  As above, except a rope.  25\'.',
	'Goggles of the Clown.  When worn, everything looks like a clown, and speaks in a mocking, clowning voice.  It is very difficult to tell people apart.  You can barely tell a knight apart from his horse (which appears as a four-legged clown).  In combat, you must make a Wisdom check every round or lose track of which clown is which.  On the upside, you are immune to the beauty of nymphs and the ugliness of catoblepas.',
	'Vial of Nightshade.  When drunk, it puts the body into a deep coma and ejects the spirit.  You can now roam around, incorporeal, until you return to your body.  There is a 1-in-6 chance each hour that some mishap befalls you (body possessed by outsider, soul lost forever, etc).  Coma lasts for 1d3 days.',
	'Grinning Amulet.  Anyone who laughs--even a snicker--near this amulet must make a save or laugh uncontrollably for the next minute.  Careful, it\'s contagious--if a player laughs during this, so does their character.',
	'Trollwax.  Tacky and unpalatable.  Anything that tastes it must succeed on a check, or be so disgusted that it cannot taste it again.  (Takes a week to fully leave the tongue.)',
	'Cheater\'s Coin.  When flipped, it will give whatever result the owner wishes.  This is not limited to heads/tails--it can also give results of king, dragon, treasury, pilgrims, etc.',
	'Boots of Independence.  When you remove these boots and fail to restrain them (put them in a pack, etc) they will walk back the way they came, all the way back to where you first put them on, with more-or-less the same cadence and sounds.  If you walked in a loop somewhere along the line, the boots will get stuck in the loop and repeat.',
	'Tiny tree.  Produces three fat apples every day (enough to feed 1 person).  Must be watered with 1 cup of blood each day, or it will die.  If dead, can be revived with water.  Probably found dead/in a chest.',
	'Skeleton gourd.  This gourd has a peephole.  Anyone holding the gourd up to their face and looking into the peephole will be paralyzed while their brain is filled with visions of dancing skeletons.',
	'Ring of Petrification.  Putting this ring on will turn a person to stone, except for the ring.  Someone else can remove the ring, and thereby return them to flesh.',
	'Party Book.  This book creates audible illusions imitating a party.  The state of the party depends on the page the book is opened to.  If the book is turned to page 1, you\'ll hear a couple people setting up silverware.  Middle of the book, raucous carousing.  Near the end, mostly snores and a few people taking shots.',
	'Quiet Bell.  This 2" tall silver bell prevents all sound within 1\'.',
	'Palette of All Colors.  Contains 7 mundane palettes (ROYGBIV) and 1 color that is invisible to humans.  If the invisible color is painted on a wall, it allows people to see through it.  Can paint up to a 3\' diameter spot, or 10 3" peepholes.  Penetrates no more than 6".  Getting it on someone\'s face blinds them.',
	'Slimming Cone.  When touched to a creature, it instantly and harmless sucks out all the excess fat from them, ejecting it onto the floor in a big mass.',
	'Grass Whistle.  When blown, roll for a random encounter.  If the location has no encounter table (some cities, maybe), the PCs will meet someone interesting who wants something.',
	'Naiad-hair Ring.  50% cursed.  When worn, PC treats all water as if it had the consistency of a gas.  (Don\'t fall off a boat.)  Water is still unbreathable.',
	'Ring of Swimming.  Wearer treats air as if it had the consistency of water.  You can "fly" by swimming through the air, but the air is too thick to breath.  Other water penalties also apply.',
	'Belt of Cat Imprisonment.  When laid on the ground, felines are compelled to sit in the center of it.  As charm.',
	'Endless Boots.  Cannot stop walking.  Will never tire from walking.  Cannot run.  Walk walk walk.',
	'Spike of Woodland Suicides.  Sort of like a hunter\'s trap.  When left in the woods, wild animals will come and impale themselves on it.  A verdant forest yield 1d10 rations worth per day, but must be moved daily.  Fey will hate you, though.',
	'Salt Block.  Any food you carry will never spoil.  Doesn\'t have to be on your person.  Applies to a captain and his ship\'s cargo, for example.',
	'Log of Alarum.  This 300 lb log protects those who sleep with their heads against it.  If they would be attacked in their sleep, the log has a 90% chance of waking them up (by making bird song).',
	'Demonic Muffin.  When eaten, reverses your gravity for 1d6 minutes.',
	'Everice.  Never melts.',
	'Chest of the Mundane.  Anything placed inside it is covered with an illusion that makes it look worthless and boring.  Currently holding 3 peridots worth 10gp each.',
	'Boots of Devouring.  Cursed.  As soon as you put one on your foot it starts fucking eating you like a garbage disposal.  Feeding it lots of booze causes it to vomit out everything in its stomache (which may include some treasure).  ',
	'Fox-in-a-Bag.  Sleeps all the time.  As soon as it touches the ground, it will run around like crazy.  Dex 18, AC as plate because of high Dexterity + foxy nature.  If you pick it up (good luck) it will fall back asleep.',
	'Feather of Bravado.  When placed in a hat, it points in the direction of the nearest deadly foe capable of killing the PCs.  When placed in the bottom of one\'s shoe, allows them to run slightly faster.',
	'Gossip Cookies.  Each one contains either a random rumor from the most relevant rumor table or "You will be killed by [random monster from most relevant random encounter table]".  50% chance of each.',
	'A small silver figurine that, when given away, will return to your pocket after 1d6 minutes.  The only way to permanently get rid of it is for the recipient to similarly give it away before the 1d6 minutes expire.   (Alternatively, the original owner could die.)  Yes, this is great for scamming people.  Apparent value: 1d100 silver.',
	'A rock that, when thrown, always hits its target.  Always.  Cannot do anything that you couldn\'t conceivably do with a really lucky throw.',
	'A saddle that turns any animal into a horse when it is strapped on.  The horse cannot remove the saddle on its own.  Currently owned by a bounty hunter who is fond of riding his bounties back to town.',
	'A key that can unlock any door, but cannot be removed from the mechanism until the door is relocked.',
	'A mug that points the way to the nearest tavern when it is balanced on its edge.',
	'An egg cup that can hatch any egg that is placed atop it.',
	'A ring that gives the wearer a magnificent mustache/beard, depending on which finger it is worn on.  The left ring finger, for example, always yields a Van Dyke.',
	'A ring that makes your eyeball pop out.  This is not a problem, and you can continue to see through the eye just fine, like a spy-eye.  Reversible if the ring is removed.',
	'A ring that makes you invisible, but not your equipment or clothing.',
	'An umbrella that allows you float downwards at 60\'/round when open, negating fall damage.',
	'Chicken Arrows (1d6).  On a hit, target must save vs fear (first arrow only).  If sat upon like an egg, quickly turns into an adult chicken.  Fletched with white feathers.',
	'Bag of Infinite Manure.  Useful for campfires.',
	'Wand of Necromantic Cooking.  Can enchant a corpse or cut of meat to cut, prepare, marinate, and cook itself.  A slaughtered pig will seek out gravy to roll around in.  Sausages will jump into the saucepan, and then seek out your plate when cooked.',
	'Omnidress.  Can turn into any type of dress (can even imitate leather armor, but not metal).',
	'Indelible Pen.  Can write on anything.  Writing is permanent.  Works 1d6 times.',
	'Ring that makes the wearer appear to be dead and rotten.',
	'Scones (1d6).  When broken in half, it erupts into 1d100 scones (10 scones = food for a day).  Alternatively, it can be eaten to restore 1d6 HP.',
	'Wooden hand.  1/day, can turn into a living-but-disembodied hand for 1 hour.  Will obey your commands for the duration.  Str 1, can climb most walls.  Int 6, can see normally, but cannot speak.',
	'Locket.  Woman\'s face inside the amulet always looks towards Meltheria.',
	'Box of paired snails.  When one snail dies, so does its mate.  Normally used to send very crude, binary messages.  There are 1d6 pairs of snails.  Feed them leaves.',
	'Hungry coin.  Cursed.  Will attempt to eat other coins that it comes into contact with.  Eats 100 coins an hour.',
	'Armor of Glamour.  Looks like a fancy dinner suit.  Is actually a suit of plate mail.',
	'Ring of Good Omen.  The first time you fail a save against a curse or other magic, the ring breaks and you instead make your save.',
	'Prayer of the Seal.  When this sheet of paper is attached to a door or portal, it become locked (until the paper is removed or destroyed.)',
	'Boots of the Aristocrat.  When you click them together, your clothes become clean, your skin becomes perfumed, and your hair is styled.',
	'Cursed matches (1d6). When lit, the match does not ignite.  Instead, whatever the PC is looking at catches fire.  (Tiny match-sized fire.  Does no damage unless allowed to progress.)',
	'Preservative jar.  Anything placed in this jar enters stasis.  Cannot hold anything bigger than a toad.  Currently holds a toad.',
	'Library Box.  When a non-magical book is placed inside it, another of the same type will be found there the next day.',
	'Monocle of Entropy.  If you stare at something long enough, it will fall over.  1 round for a candlestick, 1 minute for a sleeping cow, 1 hour for a small tree, 1 day for a cottage or large tree, 1 week for a castle.  Must be within 100\'.',
	'Girdle of Masculinity/Femininity.  Non-cursed because that\'s way more fun.',
	'Stick of the Titan.  Hits for 2d8, then breaks.',
	'Singing frog.  Knows 1d6 songs.  Good for a free round of drinks in pretty much any bar you walk in to, with only a 20% chance that someone will try to steal it from you at the end of the night.',
	'Perpetual motion machine.  Utterly unremarkable in a world filled with magic, but still cool.',
	'Seed of Moon Ice.  If dropped in a body of water, will "freeze" an area up to 20\' diameter.  If swallowed, you die.  If touched, save or die.  Leaves awesomely frozen corpses that are not cold to the touch and never thaw.',
	'Small broom.  When activated, will attempt to clean the dirtiest thing nearby.',
	'Black cat, winged.  When you tap it on the nose, it enters stasis.  (This is why you found it in a treasure chest.)',
	'Blindfold of the Spirits.  When worn, you can attack incorporeal things as if they weren\'t.  Also, you\'re blind.',
	'Night\'s Black Windchimes.  25% chance of alerting you when you would be attacked during the night.  If one of the 1d6+1 chimes is broken in half, a refreshing (but also quite cold) breeze blows through the area.',
	'Dust of Vermicide.  When thrown, does 1 damage to everything in a 5\' diameter area.  Alternatively, does 2d6 damage against a swarm.',
	'Sovereign Glue.',
	'Universal Solvent.',
	'Goblin cloak.  Invisible while in shadowy areas, but stinks like a mound of goblin shit.',
	'Miser\'s Flute.  When played, all unsecured coins in 20\' will leap up and roll after you.  They will follow you as long as you play, and as fast as normal running speed.  Uphill is fine, stairs are not.',
	'Donkey Legs.  These wooden donkey legs can be attached to anything (but are not strong enough to carry literally anything).  Once attached, the thing will follow you around like a loyal donkey.  For example, you can attach them to a heavy statue and then have it walk itself out of the dungeon.  Donkey legs are as strong as two donkeys!',
	'Giant\'s Ochre.  Anything painted with this pigment will double in size.  Washes off easily with water or sweat.  (If you paint yourself, it\'ll wash off after 1d6 rounds of sweaty combat).',
	'Mask of the Jester.  Anyone seeing it for the first time must save vs charm or be compelled to attack the wearer.',
	'Eye of Zin.  If this jewel is pressed into the forehead, the wearer\'s eyes turn jet black, they gain darkvision, and they are blinded by even small amounts of light (a nearby torch will blind them, for example).',
	'Metal Eye Mask.  Wearing this mask obscures you normal vision, but allows you to see from above, sort of like an orbital satellite\'s view.  At sea level, you can see an area 200\' in diameter, centered on the mask.',
	'Pink Bead.  When smashed on the ground, immediately turns into a huge mountain of fluffy bubbles, similar in consistency to a mass of fused marshmallows.  Can cushion a fall or block a hallway or something.  10\' in diameter, can be cut through with 6 slashing attacks, lasts 1d6 minutes.',
	'Animate rope with the personality of a loyal dog.  50\'.  Must be taught knots the way a dog must be taught tricks.'
]
gen_data['trinket'] = [
    /* Modified from DnD 5e PHB Trinkets */

    'A mummified {goblinoid_race} hand',
    'A piece of {color} crystal that faintly glows in the moonlight',
    'A {precious_material} coin minted in an unknown land',
    'A diary written in a language you don’t know',
    'A {more_precious_material} ring that never tarnishes',
    'An old chess piece made from {precious_material}',
    'A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips',
    'A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it',
    'A rope necklace from which dangles four mummified {humanoid_race} fingers',
    'The deed for a parcel of land in a realm unknown to you',
    'A 1-ounce block made from an unknown material',
    'A small cloth doll of a {humanoid_race} skewered with needles',
    'A tooth from an unknown beast',
    'An enormous scale, perhaps from a dragon',
    'A bright {color} feather',
    'An old divination card bearing your likeness',
    'A glass orb filled with moving smoke',
    'A 1-pound egg with a bright red shell',
    'A pipe that blows bubbles',
    'A glass jar containing a weird bit o f flesh floating in pickling fluid',
    'A tiny gnome-crafted music box that plays a song you dimly remember from your childhood',
    'A small wooden statuette of a smug halfling',
    'A {size_b} {more_precious_material} orb etched with strange runes',
    'A multicolored stone disk',
    'A tiny {more_precious_material} icon of a {bird_of_prey}',
    'A bag containing forty-seven humanoid teeth, one of which is rotten',
    'A shard o f obsidian that always feels warm to the touch',
    'A dragon\'s bony talon hanging from a plain leather necklace',
    'A pair of old socks',
    'A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking',
    'A {more_precious_material} badge in the shape of a {human_identifying_marks_tattoo}',
    'A knife that belonged to a relative',
    'A glass vial filled with nail clippings',
    'A rectangular metal device with two tiny metal cups on one end that throws sparks when wet',
    'A {color} glove sized for a human',
    'A vest with one hundred tiny pockets',
    'A small, weightless stone block',
    'A tiny sketch portrait of a {goblinoid_race}',
    'An empty glass vial that smells of perfume when opened',
    'A gemstone that looks like a lump of coal when examined by anyone but you',
    'A scrap of cloth from an old banner',
    'A rank insignia from a lost legionnaire',
    'A tiny {more_precious_material} bell without a clapper',
    'A mechanical canary inside a gnomish lamp',
    'A tiny chest carved to look like it has numerous feet on the bottom',
    'A dead sprite inside a clear glass bottle',
    'A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)',
    'A glass orb filled with water, in which swims a clockwork goldfish',
    'A {more_precious_material} spoon with an M engraved on the handle',
    'A whistle made from gold-colored wood',
    'A dead scarab beetle the size of your hand',
    'Two toy soldiers, one with a missing head',
    'A small box filled with different-sized buttons',
    'A candle that can’t be lit',
    'A tiny cage with no door',
    'An old key',
    'An indecipherable treasure map',
    'A hilt from a broken sword',
    'A rabbit’s foot',
    'A glass eye',
    'A cameo carved in the likeness of a hideous person',
    'A {more_precious_material} skull the size of a coin',
    'An alabaster mask',
    'A pyramid of sticky black incense that smells very bad ',
    'A nightcap that, when worn, gives you pleasant dreams',
    'A single caltrop made from bone',
    'A {more_precious_material} monocle frame without the lens',
    'A 1-inch cube, each side painted a different color',
    'A crystal knob from a door',
    'A small packet filled with {color} dust',
    'A fragment o f a beautiful song, written as musical notes on two pieces of parchment',
    'A {more_precious_material} teardrop earring made from a real teardrop ',
    'The shell of an egg painted with scenes of {humanoid_race} misery in disturbing detail',
    'A fan that, when unfolded, shows a sleeping cat',
    'A {musical_instruments}',
    'A four-leaf clover pressed inside a book discussing manners and etiquette',
    'A sheet of parchment upon which is drawn a complex mechanical contraption',
    'An ornate scabbard that fits no blade you have found so far',
    'An invitation to a party where a murder happened',
    'A {more_precious_material} pentacle with an etching of a {common_animal}\'s head in its center',
    'A purple handkerchief embroidered with the name of a powerful archmage',
    'Half o f a floorplan for a temple, castle, or some other structure',
    'A bit of folded cloth that, when unfolded, turns into a stylish cap',
    'A receipt o f deposit at a bank in a far-flung city',
    'A diary with seven missing pages',
    'An empty {precious_material} snuffbox bearing an inscription on the surface that says “dreams’’',
    'An {common_metal} holy symbol devoted to an unknown god',
    'A book that tells the story of a legendary {mysterious_persons}\'s rise and fall, with the last chapter missing',
    'A small vial labled {fantastic_animal} blood',
    'An ancient arrow of {humanoid_race} design',
    'A needle that never bends',
    'An ornate brooch of {humanoid_race} design',
    'An empty wine bottle bearing a pretty label that says, “The Wizard of Wines Winery, Red Dragon Crush, 331422-W"',
    'A mosaic tile with a multicolored, glazed surface',
    'A petrified {small_common_domestic_animal}',
    'A black pirate flag adorned with a {fantastic_animal}\'s skull and crossbones',
    'A tiny mechanical crab or spider that moves about when it’s not being observed',
    'A glass jar containing lard with a label that reads, “{fantastic_animal} Grease”',
    'A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body',
    'A metal urn containing the ashes of a {mysterious_person}'
]
gen_data['odd_treasures'] = {
	'1': ' A 50lb canvas sack of duck down feathers.  (15 gps)',
	'2': ' A soapstone jug containing a large wad of ambergris. ',
	'3': ' A famous battle banner, long lost, smells badly. ',
	'4': ' A reliquary containing the bones of an ancient holy man. ',
	'5': ' A litter of boar hound puppies.  (Six, weaned)',
	'6': ' A cloth roll of ornamental bird feathers, such as used in clothing. ',
	'7': ' A fragile bottle of a rare perfume. ',
	'8': ' Fifty pounds of fine bees wax. ',
	'9': ' 100 5x6" diamond panes of clear glass. ',
	'10': ' A very large honing stone slab of the highest quality.  1\' x3\' x 8 thick. ',
	'11': ' A 1 quart jar of rare purple snail dye. ',
	'12': ' A bolt of fine silk. ',
	'13': ' A 40lb block of rock salt. ',
	'14': ' A jagged rod of amber with a sprite entombed within.  3\' long. ',
	'15': ' An 8\' golden horn. ',
	'16': ' A crate of shoemaker’s tools.  ( last, hammers, tacks, hobnails, etc.  (400 gps)',
	'17': ' spice chest containing waxed fabric bags of rare and costly spices. ',
	'18': ' A solid jasper dinner service for 12 persons. ',
	'19': ' A sack of prized flower bulbs.  (50 gp)',
	'20': ' A 40 gallon barrel of Old Slodar’s uesgah.  (400lbs, 800gp)',
	'21': ' A very large scroll tube containing the plans for many of the ancient war engines of Armentarious. ',
	'22': ' 16 unfinished sword blanks of highest quality steel.  (220 gp)',
	'23': ' A complete barding for a war horse made of bullette horn plates. ',
	'24': ' A large, ornate field tent such as a lord would have.  Room for 12 persons.  (1200 gp)',
	'25': ' A tome of bawdy wood cut illustrations. ',
	'26': ' A ream of vellum sheets. ',
	'27': ' An ogre skull soup tureen with gold mountings. ',
	'28': ' A small sack containing 32 carved ivory mice. ',
	'29': ' An oboe-like musical instrument made from a troll’s femur. ',
	'30': ' An old boot filled with chunks of silver-bearing quartz ore.  (50 gp)',
	'31': ' A 40 lb cask of fine quality olive oil. ',
	'32': ' A water clock.  3\' x 3\' x 4\', 87 lbs. ',
	'33': ' Four pairs of snow serpent fur felt stockings.  (20 gp)',
	'34': ' An old wooden bucket full of mismatched silver spoons. ',
	'35': ' A stuffed and mounted osquip. ',
	'36': ' A pair of pole mounted fans made of giant raven feathers. ',
	'37': ' A solid gold plumb bob mounted with six cabochon sapphires. ',
	'38': ' A life sized ivory carving of a chicken. ',
	'39': ' A dozen quality daggers in a rolled up rug. ',
	'40': ' A stoppered behir horn containing 300 gp worth of powdered electrum. ',
	'41': ' Four ½ lb bricks of compressed Black Lotus pollen. ',
	'42': ' A bearer-order allowing the possessor to take ownership of a dozen slaves from Zoealage the flesh-monger. ',
	'43': ' A 3\' diameter sealed glass sphere containing water and a live ornamental fish. ',
	'44': ' A sheaf of loose leaf music written by the infamous conjurer, Wyrdlbr the Composarch. ',
	'45': ' An unhafted axe head of exceptional craftsmanship.  It’s faces are inlaid with a faience scene showing a crowd of human villagers throwing a halfling down a well. ',
	'46': ' Thirty storm giant minted gold coins, each is the size of a dinner plate and weighs 17 lbs.  The image stuck on the coins shows a giant hand flicking a human off of a table top. ',
	'47': ' A 40\' coil of rare sea shells strung on a silken cord. ',
	'48': ' A 1\' x 3\' bronze plate bearing the ancient, and secret recipe for Black Mountain Stout. ',
	'49': ' A complete set of bronze and carved stone weight training equipment issued to the 4th army of the Ancient Empire.  (900 lbs)',
	'50': ' A 6\' stack of 1 x 8" x 12\' planks of rare, scented jewel wood. ',
	'51': ' A life sized copper statue of a fat cat with amber eyes.  Purrs if stroked, does not detect as magic. ',
	'52': ' Four silk bags containing powdered illuminators pigments.  ( 1 lb each)',
	'53': ' A large bale of rare furs.  (2000 gp)',
	'54': ' A 35 lb keg of iron nails.  (30 gp)',
	'55': ' A wicker tube containing a neat stack of 38 pointed wizardly hats. ',
	'56': ' A large oak chest of carpenters tools of very good quality.  Axes, adzes, planes, saws, knives, scrapers, braces, etc.  (requires two persons to move.  250 gp)',
	'57': ' A 5\' diameter wheel of fine, aged cheese.  (75 lbs, 54 gp)',
	'58': ' 300 bottles of Burglum’s Old Quarry red wine. ',
	'59': ' A pair of large balloon leg pantaloons made of blue velvet and sewn with tiny pearls depicting flamingos in flagrante delicto. ',
	'60': ' Six giant temple candles.  Each is 6\' tall, 1\' thick, and 100 lbs.  They are made of fine white wax, rolled in gold dust, and set with emeralds.  (320 gps each. )',
	'61': ' The secret second ledger of Murhamble the Money-lender.  It reveals exactly how he has cheated the tax collector of the local lord out of thousands of gold pieces over the last decade. ',
	'62': ' A dozen costly incense cones.  12 tall, wrapped in waxed paper. ',
	'63': ' A large arbalest/bolt thrower.  It is disassembled and crated for shipping.  It requires four strong men to lift.  When reassembled, it hurls a 5\' bolt for 2d12 dmg.  3000 gps value. ',
	'64': ' A chest of stone masons tools.  Hammers, mallets, sets, chisels, wedges, etc.  ( 300 gps)',
	'65': ' An abacus with counting beads made of ivory, silver, gold, and vitrified eye balls.  (120 gps)',
	'66': ' A complete set of balls and pins used for playing bowls.  They are painted with insulting caricatures of famous kings and priests. ',
	'67': ' Fifty six 1\' x 2\' writing slates with a box containing 400 pieces of chalk. ',
	'68': ' A small leather case containing tattooing needles, (12), and colored inks. ',
	'69': ' A very large and heavy, (140 lbs), bronze mortar and pestle for mixing alchemical agents.  It is inlaid with enameled alchemical symbols.  (800 gps)',
	'70': ' A carved jade toilet stool with a hammered gold basin.  Clean. ',
	'71': ' A filthy bucket containing copper and silver coins, rings and necklaces worth 820 gps, also, 3/4 of a gallon of urine. ',
	'72': ' A large barrel of pickled eels.  (32 gps)',
	'73': ' A fabric bag containing two dozen sealed glass jars of various medicinal herbs. ',
	'74': ' A wheel barrow filled with buttons.  Ivory, bone, wood, glass, silver, and gold. ',
	'75': ' A solid gold door knocker cast in the form of a winged phallus.  (10 lbs)',
	'76': ' A butter churn made of bone slats, bound with hoops of silver.  A scrimshaw scene depicting a crowd of human villagers beating a halfling with shovels and hoes wraps around it. ',
	'77': ' A six foot long smoking pipe made of ivory, possibly a narwal horn, carved to look like a twisting serpent. ',
	'78': ' A wheeled trunk containing two dozen very detailed marionettes, and puppet show props. ',
	'79': ' A pair of mummer’s stilts.  (10 gps)',
	'80': ' A crown of severed, mummified fingers.  Each finger bears three jeweled rings.  (2200 gps)',
	'81': ' A stuffed catoblepas head mounted on an eight foot pole, with colored ribbon streamers. ',
	'82': ' An arm chair carved entirely of a single piece of coal.  Inlaid with silver runes. ',
	'83': ' An owlbear costume. ',
	'84': ' A large, boxed chess set.  All the pieces are small, dead pixies somehow sealed within glass. ',
	'85': ' A set of dies and hammers for minting the kings coinage. ',
	'86': ' A dirty canvas bag containing twenty pounds of an aphrodisiac root.  (1000gps)',
	'87': ' A table top planar armillary, bronze.  It’s dials rotate to show the relation of the inner and outer planes to the prime material, as well as the influence of the Gods and Planets, at any time during the year.  (1200 gps)',
	'88': ' A 3\' diameter globe of the Game World.  It hangs on a silver chain.  The globe shows features of the game world which are not common knowledge. ',
	'89': ' A 6 wide, 3" tall cone of loadstone.  The top of the cone attaches to a 20\' silken cord.  It takes a pull equal to 85 lbs of force to free the loadstone from any metal object. ',
	'90': ' A finely made 10\' x 12\' wool floor rug.  The center of the rug depicts a scene of siege warfare.  A halfling is being flung over a city wall by a trebuchet. ',
	'91': ' A gear-driven ships navigational calculator enclosed in a jewelwood box.  (5000 gps)',
	'92': ' One hundred and sixteen 3 white porcelain discs, each has a 1 ounce knob of electrum embedded in it’s center. ',
	'93': ' A two gallon stone ware jug containing hallucinogenic tree sap syrup.  (20 gps)',
	'94': ' The last remaining copy of Sewryd of Swrdlby’s True and Proper guide to the work of the Husbandman, and treatise on the Three Field Crop Rotation.  (500 gps)',
	'95': ' A small bag containing 58 clay sling bullets.  Each bullet has a 12 gp opal hidden inside. ',
	'96': ' A long, narrow wooden box containing forty, ½ lb rolls of quality smoking leaf. ',
	'97': ' A 1/10th scale shipbuilders model of a sailing cog.  ( 200 lbs, 2500 gps)',
	'98': ' A surveyor’s transit and measuring stakes, plus a measuring chain with marks for 1, 2, and 3 hides worth of land.  (800 gps. )'
}
